import { Logger } from "trm-commons";
import { TARSYSTEM } from "../../../client";
import { SystemConnector } from "../../../systemConnector";
import { setTransportTarget } from "./setTransportTarget";

/**
 * Resolves the landscape target system that receives the transports generated by an action.
 *
 * When the connected system has no transport targets and none was supplied, it is treated
 * as the final system of the landscape and `undefined` is returned.
 *
 * @param noInquirer Disable interactive target selection.
 * @param userInput Explicit target to validate and use.
 * @param inquirerMessage Prompt label used when interactive selection is required.
 * @param skippedMessage Warning logged when no target is available, e.g. `Install transport won't be generated.`
 * @returns The selected, valid transport target, or `undefined` for the final system.
 */
export async function setLandscapeTarget(noInquirer: boolean, userInput: TARSYSTEM | undefined, inquirerMessage: string, skippedMessage: string): Promise<TARSYSTEM | undefined> {
    Logger.loading(`Checking system target...`);
    const transportTargets = await SystemConnector.getTransportTargets();
    if (transportTargets.length === 0 && !userInput) {
        //no transport targets: system is the last in the landscape?
        Logger.info(`No transport targets in ${SystemConnector.getDest()}`);
        Logger.warning(`Is ${SystemConnector.getDest()} final system in landscape? ${skippedMessage}`, true);
        return undefined;
    }
    return setTransportTarget(noInquirer, transportTargets, userInput, inquirerMessage);
}
