import { AS4TEXT, DEVCLASS, DEVLAYER, DLVUNIT, PACKAUTHOR } from "../components"

export type SCOMPKDTLN = {
    devclass: DEVCLASS,
    ctext: AS4TEXT,
    as4user: PACKAUTHOR,
    dlvunit: DLVUNIT,
    pdevclass: DEVLAYER,
    language?: string,
    masterlang?: string,
    korrflag?: string,
    component?: string,
    namespace?: string,
    tpclass?: string,
    parentcl?: DEVCLASS,
    perminher?: string,
    intfprefx?: string,
    packtype?: string,
    packkind?: string,
    restricted?: string,
    mainpack?: string,
    srvCheck?: string,
    cliCheck?: string,
    extAlias?: string,
    projectGuid?: string,
    projectId?: string,
    projectPassdown?: string,
    switchId?: string,
    translationDepth?: string
}
