import { AS4TEXT, DEVCLASS, DLVUNIT, PARENTCL, TPCLASS } from "../components"

export type TDEVC = {
    devclass: DEVCLASS,
    parentcl: PARENTCL,
    tpclass: TPCLASS,
    dlvunit: DLVUNIT,
    ctext?: AS4TEXT,
    intsys?: string,
    consys?: string,
    korrflag?: string,
    as4user?: string,
    pdevclass?: string,
    component?: string,
    namespace?: string,
    shipment?: string,
    applicat?: string,
    errsevrty?: string,
    perminher?: string,
    intfprefx?: string,
    packtype?: string,
    restricted?: string,
    mainpack?: string,
    createdBy?: string,
    createdOn?: string,
    changedBy?: string,
    changedOn?: string,
    srvCheck?: string,
    cliCheck?: string,
    extAlias?: string,
    projectGuid?: string,
    projectPassdown?: string,
    isEnhanceable?: string,
    packageKind?: string,
    enhancedPackage?: DEVCLASS,
    accessObject?: string,
    defaultIntf?: string,
    inheritCliIntf?: string,
    techChgTstmp?: string,
    overallTstmp?: string,
    encapsulation?: string,
    dclEnabled?: string,
    subKey?: string,
    allowStatic?: string,
    switchId?: string,
    checkRule?: string
}
