import { Inquirer, Logger } from "trm-commons";
import { InstallTransport, SystemConnector } from "../../../systemConnector";
import { getE071KOwner, Transport, TrmTransportIdentifier } from "../../../transport";
import { TransportBinary, TrmPackage } from "../../../trmPackage";
import { AbstractRegistry, RegistryDeletionTransportUnavailableError } from "../../../registry";
import { packageDataFromTdevc, getPackageNamespace } from "../../../commons";
import { DEVCLASS, E071, TADIR, TDEVC, ZTRM_OBJ_LOCK } from "../../../client";
import { randomBytes } from "crypto";
import type { InstallPackageReplacements } from "../../install";
import { releaseDeletionTransport } from "./releaseDeletionTransport";
import { restoreTransport } from "./restoreTransport";
import { withScopedPrefix } from "./withScopedPrefix";
import { ActionLockScope, objectLockResource } from "./actionLocks";
import { getOwningInstallation } from "./owningInstallation";

type CleanupObject = Pick<E071, 'pgmid' | 'object' | 'objName'>;

/** Rollback state written while removing the objects of an installed release. */
export interface PackageCleanupRevert {
    /** SAP packages generated by the action. */
    sapPackages: DEVCLASS[],
    /**
     * Transportable packages created to export the objects of a temporary (`$`) installation.
     * Not part of the action's packages: they are deleted by {@link deleteCleanupStagingPackages}.
     */
    stagingPackages?: DEVCLASS[],
    /**
     * Custom namespaces imported only to stage objects of a temporary installation.
     * Deleted with the staging packages.
     */
    temporaryNamespaces?: string[],
    dele?: TransportBinary,
    /** Set before the deletion transport import: only then the objects must be restored from `dele`. */
    deleImportStarted?: boolean,
    cleanupOriginalTadir?: TADIR[],
    cleanupTemporaryPackages?: TDEVC[],
    updateCleanupTransport?: Transport,
    updateTablesBackupTransport?: Transport,
    retainedTables?: TransportBinary,
    /**
     * Tables kept installed by an upgrade, set with {@link PackageCleanupRevert.retainedTables}: a rollback of the
     * incoming import must not delete them, the backup restores their previous definition.
     */
    retainedTableObjects?: CleanupObject[],
    /** Customizing transports whose rows were added to the deletion transport. */
    cleanupCustomizingSources?: string[],
    /** Set before forwarding the deletion transport, as the TMS queue may change even when the call fails. */
    deleInTargetTms?: boolean
}

/** Minimum workflow context needed to remove an installed release from the target system. */
export interface PackageCleanupContext {
    lockScope?: ActionLockScope,
    rawInput: {
        packageData: {
            name: string,
            registry: AbstractRegistry
        },
        contextData?: {
            noInquirer?: boolean,
            /** Packages installed on the target system: SAP packages of other installations are never cleaned up. */
            systemPackages?: TrmPackage[]
        }
    },
    runtime?: {
        /** Installed release whose objects are removed. */
        update: TrmPackage,
        /** Install package mappings recorded for the installed release. */
        previousInstallPackages: InstallPackageReplacements[],
        /** Transports recorded for the installed release; its customizing comes from the `CUST` ones. */
        previousInstallTransports?: InstallTransport[],
        dele?: Transport,
        /**
         * Objects already deleted by this run (the deletes of the TRM packages installed underneath):
         * the system may still list them for a while after their deletion transport import.
         */
        deletedObjects?: Pick<E071, 'pgmid' | 'object' | 'objName'>[]
    },
    revert?: PackageCleanupRevert
}

/** What remains on the system once the cleanup is complete. */
export type PackageCleanupTarget = {
    /** Objects shipped by the incoming release. Empty when uninstalling. */
    incomingObjects: TADIR[],
    /** SAP packages that hold the incoming release. Empty when uninstalling. */
    keptDevclasses: string[],
    /** Logger/Inquirer prefix shown while the cleanup runs. */
    prefix: string,
    /** Action name used in abort messages, e.g. `Update`. */
    actionName: string,
    /**
     * When `true`, an unauthorized deletion transport request is rethrown after restoring
     * object assignments. Otherwise it only logs a manual cleanup warning.
     */
    requireDeletion: boolean,
    /**
     * When `true`, the customizing rows shipped by the installed release are kept.
     * Otherwise they are always deleted, without asking.
     */
    keepCustomizing?: boolean,
    /**
     * Table content the incoming release imports after the cleanup: rows it ships again are rewritten,
     * so only the others are listed and confirmed. A row without `tabkey` is a whole table.
     * Empty when uninstalling.
     */
    incomingCustomizing?: CustomizingRow[]
}

/** A row of table content carried by a transport: a key of a table, or the whole table without `tabkey`. */
export type CustomizingRow = { table: string, tabkey?: string };

function normalize(value: string): string {
    return value.trim().toUpperCase();
}

function objectKey(object: CleanupObject): string {
    return `${normalize(object.pgmid)}\u0000${normalize(object.object)}\u0000${normalize(object.objName)}`;
}

function isDevclass(object: CleanupObject): boolean {
    return normalize(object.pgmid) === 'R3TR' && normalize(object.object) === 'DEVC';
}

function isNamespace(object: CleanupObject): boolean {
    return normalize(object.pgmid) === 'R3TR' && normalize(object.object) === 'NSPC';
}

/** Custom (`/XXX/`) namespace of a SAP package, if any. */
function getCustomNamespace(devclass: string): string | undefined {
    try {
        const namespace = getPackageNamespace(devclass);
        return namespace.startsWith('/') ? namespace : undefined;
    } catch (e) {
        // devclass doesn't use a custom namespace
        return undefined;
    }
}

/**
 * TRM packages, other than `installed`, installed in one of `devclasses` (normalized SAP package
 * names, usually the live subtree of the installed release).
 */
export function getPackagesInstalledIn(systemPackages: TrmPackage[], installed: TrmPackage, devclasses: Set<string>): TrmPackage[] {
    const installedDevclass = normalize(installed.getDevclass() || '');
    return systemPackages.filter(pkg => {
        const devclass = normalize(pkg.getDevclass() || '');
        return devclass && devclass !== installedDevclass && devclasses.has(devclass);
    });
}

/**
 * Objects of the installed transport the cleanup deletes, and the namespaces it carries.
 */
async function readInstalledTransportObjects(installed: TrmPackage): Promise<{ previousNamespaces: E071[], previousTransportObjects: E071[] }> {
    const installedTransportObjects = installed.getTransport()
        ? await installed.getTransport().getE071()
        : [];
    // Table content (entries with E071K keys, e.g. a landscape transport carrying the CUST
    // transports) is deleted by key through the customizing transports. Added without
    // its keys, it would request the deletion of the whole table object.
    const keyedObjects = new Set(installed.getTransport() && installedTransportObjects.length > 0
        ? (await installed.getTransport().getE071K()).map(key => objectKey(getE071KOwner(key)))
        : []);
    return {
        // A namespace may be used by packages outside this installation: it's only deleted
        // through the usage check, never because the installed transport carries it.
        previousNamespaces: installedTransportObjects.filter(object => !keyedObjects.has(objectKey(object)) && isNamespace(object)),
        // Translations (LANG rows, e.g. a landscape transport carrying the LANG transport) are deleted
        // with their objects: SAP rejects them as deletion entries.
        previousTransportObjects: installedTransportObjects.filter(object => !keyedObjects.has(objectKey(object))
            && !isNamespace(object) && normalize(object.pgmid) !== 'LANG')
    };
}

type InstallationTree = {
    /** SAP packages of the installation, live subpackages included, by normalized name. */
    previousDevclasses: Map<string, string>,
    /** Normalized SAP packages recorded by the install (mappings and installed transport). */
    installedDevclasses: Set<string>,
    /** Normalized parent of each live subpackage. */
    packageParents: Map<string, string>,
    /** Other TRM packages installed in the installation's SAP packages, by normalized SAP package. */
    otherInstallations: Map<string, TrmPackage>,
    /** Whether a SAP package belongs to another TRM package installed underneath. */
    isOtherInstallation: (devclass: string) => boolean
};

/** SAP packages of an installed release, as they are on the system now. */
async function readInstallationTree(
    installed: TrmPackage,
    previousInstallPackages: InstallPackageReplacements[],
    previousTransportObjects: CleanupObject[],
    deletedObjects: CleanupObject[],
    systemPackages: TrmPackage[]
): Promise<InstallationTree> {
    const previousDevclasses = new Map<string, string>();
    previousInstallPackages.forEach(replacement => {
        previousDevclasses.set(normalize(replacement.installDevclass), replacement.installDevclass);
    });
    // Older installations that kept the publisher package names have no replacement rows.
    if (previousDevclasses.size === 0 && installed.getDevclass()) {
        const previousRoot = installed.getDevclass();
        previousDevclasses.set(normalize(previousRoot), previousRoot);
    }
    previousTransportObjects.forEach(object => {
        if (isDevclass(object)) {
            previousDevclasses.set(normalize(object.objName), object.objName);
        }
    });
    const installedDevclasses = new Set(previousDevclasses.keys());

    // Installation mappings do not include subpackages created locally afterwards.
    // Inspect the live hierarchy even when the installation keeps its root package.
    const deletedKeys = new Set(deletedObjects.map(objectKey));
    const packageParents = new Map<string, string>();
    for (const devclass of Array.from(previousDevclasses.values())) {
        for (const subpackage of await SystemConnector.getSubpackages(devclass)) {
            if (deletedKeys.has(objectKey({ pgmid: 'R3TR', object: 'DEVC', objName: subpackage.devclass }))) {
                continue;
            }
            const key = normalize(subpackage.devclass);
            previousDevclasses.set(key, subpackage.devclass);
            if (subpackage.parentcl) {
                packageParents.set(key, normalize(subpackage.parentcl));
            }
        }
    }

    // Other TRM packages installed underneath have their own lifecycle and are ignored: the delete
    // action deletes them first, an upgrade removes everything else. Their ancestors stay as packages.
    const otherInstallations = new Map(getPackagesInstalledIn(
        systemPackages, installed, new Set(previousDevclasses.keys())
    ).map(pkg => [normalize(pkg.getDevclass()), pkg]));
    const isOtherInstallation = (devclass: string): boolean => {
        const visited = new Set<string>();
        let current = normalize(devclass);
        while (current && !visited.has(current)) {
            if (otherInstallations.has(current)) {
                return true;
            }
            visited.add(current);
            current = packageParents.get(current);
        }
        return false;
    };
    return { previousDevclasses, installedDevclasses, packageParents, otherInstallations, isOtherInstallation };
}

/**
 * Installed objects now in a SAP package outside the installation, or in the SAP package of
 * another TRM package installed underneath.
 */
async function readRelocatedObjects(
    objects: CleanupObject[],
    tree: Pick<InstallationTree, 'previousDevclasses' | 'isOtherInstallation'>
): Promise<TADIR[]> {
    return (await SystemConnector.getExistingObjects(objects
        .filter(object => normalize(object.pgmid) === 'R3TR' && !isDevclass(object))
        .map(object => ({ pgmid: object.pgmid, object: object.object, objName: object.objName, devclass: '' }))))
        .filter(object => object.devclass && (!tree.previousDevclasses.has(normalize(object.devclass)) || tree.isOtherInstallation(object.devclass)));
}

/**
 * Locks on those of `objects` that removing `installed` certainly deletes: the objects of its
 * installed transport still in its SAP packages. These would abort the cleanup at its objects
 * lock check, so they can be checked before asking anything. Objects added locally or moved
 * outside the installation are left out, as the cleanup may keep them.
 */
export async function getInstalledObjectsLocks(
    installed: TrmPackage,
    previousInstallPackages: InstallPackageReplacements[],
    systemPackages: TrmPackage[],
    objects: CleanupObject[]
): Promise<ZTRM_OBJ_LOCK[]> {
    if (objects.length === 0) {
        return [];
    }
    const { previousTransportObjects } = await readInstalledTransportObjects(installed);
    const installedKeys = new Set(previousTransportObjects.map(objectKey));
    const candidates = new Map(objects
        .filter(object => installedKeys.has(objectKey(object)))
        .map(object => [objectKey(object), object]));
    if (candidates.size === 0) {
        return [];
    }
    const tree = await readInstallationTree(installed, previousInstallPackages, previousTransportObjects, [], systemPackages);
    (await readRelocatedObjects(Array.from(candidates.values()), tree)).forEach(object => candidates.delete(objectKey(object)));
    if (candidates.size === 0) {
        return [];
    }
    return SystemConnector.getObjectsLocks(Array.from(candidates.values(), object => ({
        PGMID: object.pgmid,
        OBJECT: object.object,
        OBJ_NAME: object.objName
    })));
}

/** Deletes every temporary package, reporting the first failure after the cleanup pass. */
export async function deleteTemporaryCleanupPackages(
    temporaryPackages: Array<Pick<E071, 'objName'>>
): Promise<void> {
    let firstError: unknown;
    for (const devclass of temporaryPackages) {
        try {
            await SystemConnector.deleteTemporaryPackage(devclass.objName);
        } catch (error) {
            firstError ||= error;
        }
    }
    if (firstError) {
        throw firstError;
    }
}

/**
 * Deletes the staging packages created by the cleanup, once their objects were assigned back.
 * Every package is attempted; the first failure is thrown afterwards.
 */
export async function deleteCleanupStagingPackages(context: PackageCleanupContext): Promise<void> {
    let firstError: unknown;
    for (const devclass of context.revert.stagingPackages || []) {
        try {
            if (!(await SystemConnector.getDevclass(devclass))) {
                continue;
            }
            const objects = (await SystemConnector.getDevclassObjects(devclass, false)).filter(object => !isDevclass(object));
            if (objects.length > 0) {
                throw new Error(`SAP package ${devclass} still contains ${objects.length} objects: manual cleanup is necessary.`);
            }
            Logger.loading(`Deleting package ${devclass}...`, true);
            const transport = await Transport.createToc({
                text: `@X1@TRM (DELE) ${context.rawInput.packageData.name} ${context.runtime.update.manifest.get().version}`,
                target: SystemConnector.getDest()
            });
            try {
                await transport.addObjects([{ pgmid: 'R3TR', object: 'DEVC', objName: devclass }], false);
                await releaseDeletionTransport(transport, context.rawInput.packageData.registry, context, false);
            } catch (error) {
                try {
                    if (await transport.canBeDeleted()) {
                        await transport.delete();
                    }
                } catch (deleteError) {
                    Logger.warning(`Could not delete transport ${transport.trkorr}: ${String(deleteError)}`, { important: true });
                }
                throw error;
            }
        } catch (error) {
            Logger.warning(`Could not delete SAP package ${devclass}, manual cleanup might be necessary.`, { important: true });
            firstError ||= error;
        }
    }
    // Namespaces imported for the staging go once no package uses them.
    for (const namespace of context.revert.temporaryNamespaces || []) {
        try {
            if (!(await SystemConnector.getNamespace(namespace))) {
                continue;
            }
            const packages = await SystemConnector.getNamespacePackages(namespace);
            if (packages.length > 0) {
                throw new Error(`Namespace ${namespace} is still used by SAP packages ${packages.map(o => o.devclass).join(', ')}.`);
            }
            Logger.loading(`Deleting namespace ${namespace}...`, true);
            const transport = await Transport.createToc({
                text: `@X1@TRM (DELE) ${context.rawInput.packageData.name} ${context.runtime.update.manifest.get().version}`,
                target: SystemConnector.getDest()
            });
            try {
                await transport.addObjects([{ pgmid: 'R3TR', object: 'NSPC', objName: namespace }], false);
                await releaseDeletionTransport(transport, context.rawInput.packageData.registry, context, false);
            } catch (error) {
                try {
                    if (await transport.canBeDeleted()) {
                        await transport.delete();
                    }
                } catch (deleteError) {
                    Logger.warning(`Could not delete transport ${transport.trkorr}: ${String(deleteError)}`, { important: true });
                }
                throw error;
            }
        } catch (error) {
            Logger.warning(`Could not delete namespace ${namespace}, imported for the cleanup: manual cleanup might be necessary.`, { important: true });
            firstError ||= error;
        }
    }
    if (firstError) {
        throw firstError;
    }
}

async function restoreCleanupPackages(context: PackageCleanupContext): Promise<void> {
    // Snapshots are stored in deletion order: reverse it to recreate parents first.
    let firstError: unknown;
    for (const pkg of [...(context.revert.cleanupTemporaryPackages || [])].reverse()) {
        try {
            if (await SystemConnector.getDevclass(pkg.devclass)) {
                continue;
            }
            await SystemConnector.createPackage({
                ...packageDataFromTdevc(pkg, {
                    devclass: pkg.devclass,
                    ctext: pkg.ctext || '',
                    as4user: pkg.as4user || SystemConnector.getLogonUser(),
                    dlvunit: pkg.dlvunit,
                    pdevclass: pkg.pdevclass || ''
                }),
                parentcl: pkg.parentcl,
                tpclass: pkg.tpclass
            });
        } catch (error) {
            firstError ||= error;
        }
    }
    if (firstError) {
        throw firstError;
    }
}

async function restoreCleanupAssignments(context: PackageCleanupContext, restorePackages: boolean): Promise<void> {
    if (restorePackages) {
        await restoreCleanupPackages(context);
    }
    await restoreTadirAssignments(context.revert.cleanupOriginalTadir || []);
}

/**
 * Assigns the objects that still exist back to their previous TADIR rows. Every object is
 * attempted; the first failure is thrown afterwards.
 */
export async function restoreTadirAssignments(originals: TADIR[]): Promise<void> {
    if (originals.length === 0) {
        return;
    }
    const existing = new Set((await SystemConnector.getExistingObjects(originals)).map(objectKey));
    let firstError: unknown;
    for (const object of originals) {
        if (existing.has(objectKey(object))) {
            try {
                await SystemConnector.tadirInterface(object);
            } catch (error) {
                firstError ||= error;
            }
        }
    }
    if (firstError) {
        throw firstError;
    }
}

/**
 * Releases a transport of copies with the previous definition of the retained tables,
 * so a rollback can restore them without dropping their data.
 */
async function backupRetainedTables(
    context: PackageCleanupContext,
    retainedTables: CleanupObject[]
): Promise<void> {
    Logger.loading(`Backing up ${retainedTables.length} retained tables...`, true);
    const backup = await Transport.createToc({
        text: `@X1@TRM (BKP) ${context.rawInput.packageData.name} ${context.runtime.update.manifest.get().version}`,
        target: SystemConnector.getDest()
    });
    context.revert.updateTablesBackupTransport = backup;
    await backup.addObjects(retainedTables.map(object => ({
        pgmid: object.pgmid,
        object: object.object,
        objName: object.objName
    })), false);
    await backup.release(false, true);
    context.revert.retainedTables = {
        trkorr: backup.trkorr,
        entries: undefined,
        binaries: (await backup.download()).binaries
    };
    context.revert.retainedTableObjects = retainedTables.map(object => ({
        pgmid: object.pgmid,
        object: object.object,
        objName: object.objName
    }));
}

/**
 * Customizing transports of the installed release whose rows must be deleted. Only transports
 * recorded at install time and still on the system count.
 */
async function getCustomizingSources(context: PackageCleanupContext, target: PackageCleanupTarget): Promise<string[]> {
    const sources: string[] = [];
    for (const transport of context.runtime.previousInstallTransports || []) {
        if (normalize(transport.trmType || '') !== TrmTransportIdentifier.CUST) {
            continue;
        }
        if (await new Transport(transport.trkorr).getE070()) {
            sources.push(transport.trkorr);
        } else {
            Logger.warning(`Customizing transport ${transport.trkorr} is no longer on ${SystemConnector.getDest()}: its rows can't be deleted.`, { important: true });
        }
    }
    if (sources.length === 0) {
        return [];
    }
    if (target.keepCustomizing) {
        Logger.warning(`Keeping customizing of ${sources.length} transports (${sources.join(', ')}).`, { important: true });
        return [];
    }
    return sources;
}

/**
 * Lists the customizing rows the cleanup deletes and asks to continue: always for a generic key or a
 * whole table, which also delete rows not shipped by the package (default no); otherwise only when
 * the incoming release doesn't ship customizing that rewrites them (default yes).
 * Without prompts, it only warns.
 */
async function confirmCustomizingDeletion(context: PackageCleanupContext, target: PackageCleanupTarget, sources: string[]): Promise<void> {
    const rows: CustomizingRow[] = [];
    for (const trkorr of sources) {
        rows.push(...await new Transport(trkorr).getCustomizingKeys());
    }
    const generic = rows.filter(row => row.tabkey === undefined || row.tabkey.includes('*'));
    // Rows the incoming release ships again are rewritten by its import: only the others are lost.
    const incoming = target.incomingCustomizing || [];
    const wholeTables = new Set(incoming.filter(row => row.tabkey === undefined).map(row => normalize(row.table)));
    const incomingKeys = new Set(incoming.filter(row => row.tabkey !== undefined).map(row => `${normalize(row.table)}\u0000${row.tabkey}`));
    const lost = rows.filter(row => !generic.includes(row)
        && !wholeTables.has(normalize(row.table)) && !incomingKeys.has(`${normalize(row.table)}\u0000${row.tabkey}`));
    const listed = [...generic, ...lost];
    if (listed.length === 0) {
        Logger.log(`Deleting ${rows.length} customizing rows rewritten by the incoming release`, true);
        return;
    }
    const label = (row: CustomizingRow) => row.tabkey === undefined ? `${row.table} (all rows)` : `${row.table} ${row.tabkey}`;
    const shown = listed.slice(0, 20).map(label);
    if (listed.length > shown.length) {
        shown.push(`...and ${listed.length - shown.length} more`);
    }
    const name = context.rawInput.packageData.name;
    const version = context.runtime.update.manifest.get().version;
    const message = generic.length > 0
        ? `${generic.length} customizing ${generic.length === 1 ? 'entry' : 'entries'} of ${name} v${version} ${generic.length === 1 ? 'uses' : 'use'} a generic key or a whole table: every matching row will be deleted, including rows not shipped by ${name}`
        : `${listed.length} customizing ${listed.length === 1 ? 'row' : 'rows'} shipped by ${name} v${version} will be deleted${incoming.length > 0 ? ' (not shipped by the new release)' : ''}`;
    Logger.warning(`${message}:\n${shown.join('\n')}`, { important: true });
    if (context.rawInput.contextData?.noInquirer) {
        return;
    }
    const { deleteCustomizing } = await Inquirer.prompt({
        name: 'deleteCustomizing',
        type: 'confirm',
        message: `${message}. Continue?`,
        default: generic.length === 0
    });
    if (!deleteCustomizing) {
        throw new Error(`${target.actionName} aborted.`);
    }
}

/**
 * Imports a custom namespace missing on the system, with the repair license of the installed
 * release, so its objects can be staged in a package of the namespace.
 */
async function importStagingNamespace(context: PackageCleanupContext, namespace: string): Promise<void> {
    if (await SystemConnector.getNamespace(namespace)) {
        return;
    }
    const manifestNamespace = context.runtime.update.manifest.get().namespace;
    if (!manifestNamespace?.replicense || normalize(manifestNamespace.ns || '') !== normalize(namespace)) {
        throw new Error(`Namespace ${namespace} doesn't exist in ${SystemConnector.getDest()} and its repair license is unknown: add it in SE03 to delete the objects of the local installation.`);
    }
    Logger.loading(`Importing namespace ${namespace}...`, true);
    // Track before the mutating await: SAP may commit the namespace and still fail the response.
    context.revert.temporaryNamespaces ||= [];
    context.revert.temporaryNamespaces.push(namespace);
    await SystemConnector.addNamespace(namespace, manifestNamespace.replicense, manifestNamespace.texts.map(o => ({
        namespace,
        spras: o.language,
        descriptn: o.description,
        owner: o.owner
    })));
}

/** Creates a short-lived transportable package, in `namespace` when set, so CTS can export local objects. */
async function createStagingPackage(context: PackageCleanupContext, namespace: string): Promise<string> {
    const prefix = namespace ? `${namespace}TRMD_` : 'ZTRM_DELE_';
    // DEVCLASS allows 30 characters.
    const hexLength = Math.min(16, 30 - prefix.length);
    let stagingDevclass: string;
    do {
        stagingDevclass = `${prefix}${randomBytes(8).toString('hex').toUpperCase().substring(0, hexLength)}`;
    } while (await SystemConnector.getDevclass(stagingDevclass));
    Logger.loading(`Creating package ${stagingDevclass}...`, true);
    // Track before the mutating await because SAP may commit the package
    // even when the connector response fails.
    context.revert.stagingPackages ||= [];
    context.revert.stagingPackages.push(stagingDevclass);
    await SystemConnector.createPackage({
        devclass: stagingDevclass,
        ctext: 'TRM upgrade cleanup',
        as4user: SystemConnector.getLogonUser(),
        dlvunit: 'HOME',
        pdevclass: await SystemConnector.getDefaultTransportLayer()
    });
    await SystemConnector.tadirInterface({
        pgmid: 'R3TR', object: 'DEVC', objName: stagingDevclass,
        devclass: stagingDevclass, srcsystem: 'TRM'
    });
    return stagingDevclass;
}

/**
 * Removes the objects of the installed release (`context.runtime.update`) that are not part
 * of `target`, through a deletion transport generated by the registry.
 *
 * Shared by upgrades, where the target is the incoming release, and by uninstalls, where the
 * target is empty. It also removes SAP packages left empty, locally added objects (after
 * confirmation), the package namespace when no other package uses it, and the customizing rows
 * of the installed release. Tables shipped again by the target are kept and
 * backed up so a rollback preserves their data.
 */
export async function cleanupInstalledPackage(context: PackageCleanupContext, target: PackageCleanupTarget): Promise<void> {
    await withScopedPrefix(target.prefix, async () => {
        const installed = context.runtime.update;
        //1- generate dummy transport
        Logger.loading(`Generating transport...`);
        const dummy = await Transport.createToc({
            text: `@X1@TRM (DELE) ${context.rawInput.packageData.name} ${installed.manifest.get().version}`,
            target: SystemConnector.getDest()
        });
        context.revert.updateCleanupTransport = dummy;
        const { previousNamespaces, previousTransportObjects } = await readInstalledTransportObjects(installed);
        const incomingObjects = target.incomingObjects;
        // Tables shipped again by the new release are adjusted by its import instead of
        // being dropped and re-created, which would lose their data.
        const incomingKeys = new Set(incomingObjects.map(objectKey));
        const retainedTables = previousTransportObjects.filter(object =>
            normalize(object.pgmid) === 'R3TR' && normalize(object.object) === 'TABL'
            && incomingKeys.has(objectKey(object)));
        const retainedKeys = new Set(retainedTables.map(objectKey));
        retainedTables.forEach(object => Logger.log(`Keeping table ${object.objName} (present in new release)`, true));
        const currentDevclasses = new Set(target.keptDevclasses.map(normalize));
        const deletedKeys = new Set((context.runtime.deletedObjects || []).map(objectKey));
        const { previousDevclasses, installedDevclasses, packageParents, otherInstallations, isOtherInstallation } = await readInstallationTree(
            installed,
            context.runtime.previousInstallPackages,
            previousTransportObjects,
            context.runtime.deletedObjects || [],
            context.rawInput.contextData?.systemPackages || []
        );
        const generatedDevclasses = new Set(context.revert.sapPackages.map(normalize));
        otherInstallations.forEach(pkg => Logger.log(`Ignoring SAP package ${pkg.getDevclass()}: TRM package ${pkg.packageName} is installed there`, true));

        // Local additions remain cleanup candidates even when reused as incoming targets.
        // The first local package owns the decision for its locally added descendants.
        const cleanupGroups = new Map<string, Set<string>>();
        for (const normalizedDevclass of previousDevclasses.keys()) {
            const locallyAdded = !installedDevclasses.has(normalizedDevclass);
            if (generatedDevclasses.has(normalizedDevclass) || (!locallyAdded && currentDevclasses.has(normalizedDevclass))
                || isOtherInstallation(normalizedDevclass)) {
                continue;
            }
            let root = normalizedDevclass;
            const visited = new Set([root]);
            let parent = packageParents.get(root);
            while (parent && previousDevclasses.has(parent) && !generatedDevclasses.has(parent)
                && (!installedDevclasses.has(parent) === locallyAdded)
                && (locallyAdded || !currentDevclasses.has(parent)) && !visited.has(parent)) {
                root = parent;
                visited.add(root);
                parent = packageParents.get(root);
            }
            if (!cleanupGroups.has(root)) {
                cleanupGroups.set(root, new Set());
            }
            cleanupGroups.get(root).add(normalizedDevclass);
        }

        const changedDevclassesToDelete: string[] = [];
        const extraObjectsToDelete = new Map<string, CleanupObject>();
        for (const [root, group] of cleanupGroups) {
            const devclass = previousDevclasses.get(root);

            // Only objects outside both releases need an extra cleanup decision.
            const objectsAfterImport = new Map<string, TADIR>();
            for (const member of group) {
                for (const object of await SystemConnector.getDevclassObjects(previousDevclasses.get(member), false)) {
                    // Package definitions follow the decision for the whole subtree; namespaces the usage check.
                    if (!isDevclass(object) && !isNamespace(object) && !deletedKeys.has(objectKey(object))) {
                        objectsAfterImport.set(objectKey(object), object);
                    }
                }
            }
            previousTransportObjects.forEach(object => objectsAfterImport.delete(objectKey(object)));
            incomingObjects.forEach(object => {
                objectsAfterImport.delete(objectKey(object));
            });

            // Every locally added package definition is an extra object, including
            // the root of this cleanup group, regardless of whether it has contents.
            const packagesToRemove = Array.from(group).filter(member => !currentDevclasses.has(member));
            const extraObjectCount = objectsAfterImport.size + packagesToRemove.filter(member => !installedDevclasses.has(member)).length;
            if (extraObjectCount > 0) {
                const extraObjectsMessage = `Cleanup of SAP package ${devclass}${group.size > 1 ? ' and its subpackages' : ''} will delete ${extraObjectCount} extra objects outside this installation`;
                // Name the objects, so the user can tell local developments worth keeping.
                const extraObjects = [
                    ...Array.from(objectsAfterImport.values()).map(object => `${object.pgmid} ${object.object} ${object.objName}`),
                    ...packagesToRemove.filter(member => !installedDevclasses.has(member)).map(member => `R3TR DEVC ${previousDevclasses.get(member)}`)
                ];
                Logger.warning(`${extraObjectsMessage}:\n${extraObjects.join('\n')}`, { important: true });
                const { deleteExtraObjects } = context.rawInput.contextData.noInquirer
                    ? { deleteExtraObjects: true }
                    : await Inquirer.prompt({
                        name: 'deleteExtraObjects',
                        type: 'confirm',
                        message: `${extraObjectsMessage}. Continue?`,
                        default: true
                    });
                if (!deleteExtraObjects) {
                    continue;
                }
                objectsAfterImport.forEach((object, key) => extraObjectsToDelete.set(key, {
                    pgmid: object.pgmid,
                    object: object.object,
                    objName: object.objName
                }));
            }
            changedDevclassesToDelete.push(...packagesToRemove.map(member => previousDevclasses.get(member)));
        }

        // A retained child still needs its ancestors, including when cleanup was declined.
        const deletableDevclasses = new Set(changedDevclassesToDelete.map(normalize));
        for (const devclass of previousDevclasses.keys()) {
            if (deletableDevclasses.has(devclass)) {
                continue;
            }
            const visited = new Set<string>();
            let parent = packageParents.get(devclass);
            while (parent && !visited.has(parent)) {
                visited.add(parent);
                deletableDevclasses.delete(parent);
                parent = packageParents.get(parent);
            }
        }
        const packagesToDelete = changedDevclassesToDelete.filter(devclass => deletableDevclasses.has(normalize(devclass)));

        // A namespace can only be cleaned up alongside its last remaining package: any other SAP
        // package in it (TDEVC NAMESPACE), installed by TRM or not, keeps it. Namespaces of the
        // incoming release are kept, as its packages may not have been imported yet.
        const incomingNamespaces = new Set(target.keptDevclasses.map(getCustomNamespace).filter(Boolean).map(normalize));
        const namespaceCandidates = new Map<string, string>();
        previousNamespaces.forEach(object => namespaceCandidates.set(normalize(object.objName), object.objName));
        const rootNamespace = installed.getDevclass() ? getCustomNamespace(installed.getDevclass()) : undefined;
        if (rootNamespace) {
            namespaceCandidates.set(normalize(rootNamespace), rootNamespace);
        }
        const deletingDevclasses = new Set(packagesToDelete.map(normalize));
        const namespacesToDelete: string[] = [];
        for (const [key, namespace] of namespaceCandidates) {
            if (incomingNamespaces.has(key)) {
                Logger.log(`Keeping namespace ${namespace}: used by the incoming release`, true);
                continue;
            }
            try {
                if (!(await SystemConnector.getNamespace(namespace))) {
                    continue;
                }
                const remainingPackages = (await SystemConnector.getNamespacePackages(namespace))
                    .filter(pkg => !deletingDevclasses.has(normalize(pkg.devclass)));
                if (remainingPackages.length === 0) {
                    namespacesToDelete.push(namespace);
                } else {
                    Logger.log(`Keeping namespace ${namespace}: still used by SAP packages ${remainingPackages.map(pkg => pkg.devclass).join(', ')}`, true);
                }
            } catch (e) {
                Logger.warning(`Keeping namespace ${namespace}: its usage could not be checked (${String(e)})`, { important: true });
            }
        }

        // Installed objects moved to a package outside this installation (customer development)
        // are kept unless confirmed; those now in another TRM package belong to it and are kept.
        const relocatedObjects = await readRelocatedObjects(
            previousTransportObjects.filter(object => !retainedKeys.has(objectKey(object))),
            { previousDevclasses, isOtherInstallation }
        );
        const movedKeys = new Set<string>();
        const movedObjects: TADIR[] = [];
        for (const object of relocatedObjects) {
            if (isOtherInstallation(object.devclass)) {
                Logger.log(`Keeping ${object.pgmid} ${object.object} ${object.objName}: it's in SAP package ${object.devclass} of another TRM package`, true);
                movedKeys.add(objectKey(object));
                continue;
            }
            // An object now shipped by another installed TRM package belongs to it: never offer to delete it.
            const owner = await getOwningInstallation(object.devclass, context.rawInput.contextData?.systemPackages || [], installed);
            if (owner) {
                Logger.info(`Keeping ${object.pgmid} ${object.object} ${object.objName}: it belongs to TRM package ${owner.packageName} (SAP package ${object.devclass}).`);
                movedKeys.add(objectKey(object));
                continue;
            }
            movedObjects.push(object);
        }
        if (movedObjects.length > 0) {
            movedObjects.forEach(object => Logger.warning(`${object.pgmid} ${object.object} ${object.objName} was moved to SAP package ${object.devclass}, outside this installation`));
            const { deleteMovedObjects } = context.rawInput.contextData.noInquirer
                ? { deleteMovedObjects: false }
                : await Inquirer.prompt({
                    name: 'deleteMovedObjects',
                    type: 'confirm',
                    message: `Delete ${movedObjects.length} installed objects moved outside this installation too?`,
                    default: false
                });
            if (!deleteMovedObjects) {
                movedObjects.forEach(object => movedKeys.add(objectKey(object)));
                Logger.warning(`Keeping ${movedObjects.length} objects moved outside this installation.`, { important: true });
            }
        }

        const customizingSources = await getCustomizingSources(context, target);
        if (customizingSources.length > 0) {
            await confirmCustomizingDeletion(context, target, customizingSources);
        }

        const additionalObjects = [...extraObjectsToDelete.values(), ...packagesToDelete.map(devclass => ({
            pgmid: 'R3TR',
            object: 'DEVC',
            objName: devclass
        })), ...namespacesToDelete.map(namespace => ({
            pgmid: 'R3TR',
            object: 'NSPC',
            objName: namespace
        }))];
        // Validate the complete deletion selection before adding anything to the transport.
        const deletionObjects = new Map([...previousTransportObjects, ...additionalObjects]
            .filter(object => !retainedKeys.has(objectKey(object)) && !movedKeys.has(objectKey(object)))
            .map(object => [objectKey(object), object]));
        // TRM comment rows of the installed transport are not objects to delete.
        const hasObjectsToDelete = Array.from(deletionObjects.values()).some(object => normalize(object.pgmid) !== '*');
        if (!hasObjectsToDelete && retainedTables.length === 0 && customizingSources.length === 0) {
            Logger.warning(`Nothing to delete for package ${context.rawInput.packageData.name}: deletion transport was not generated. Manual cleanup of previous release install might be necessary.`, { important: true });
            try {
                if (await dummy.canBeDeleted()) {
                    await dummy.delete();
                    context.revert.updateCleanupTransport = undefined;
                }
            } catch (e) {
                Logger.warning(`Could not delete transport ${dummy.trkorr}: ${String(e)}`, { important: true });
            }
            return;
        }
        await context.lockScope.acquire([
            // TRM comment rows are not objects and are shared by every package.
            ...Array.from(deletionObjects.values()).filter(object => normalize(object.pgmid) !== '*').map(objectLockResource),
            ...Array.from(deletionObjects.values())
                .filter(isDevclass)
                .map(object => ({ type: "DEVCLASS" as const, name: object.objName }))
        ]);
        if (deletionObjects.size > 0) {
            Logger.loading(`Checking cleanup objects locks...`, true);
            const locks = await SystemConnector.getObjectsLocks(Array.from(deletionObjects.values(), object => ({
                PGMID: object.pgmid,
                OBJECT: object.object,
                OBJ_NAME: object.objName
            })));
            if (locks.length > 0) {
                locks.forEach(lock => Logger.error(`${lock.pgmid} ${lock.object} ${lock.objName} is currently locked in transport ${lock.trkorr}`, { important: true }));
                throw new Error(`${target.actionName} aborted. To continue, all cleanup objects and SAP packages must be released`);
            }
        }
        const temporaryPackages = Array.from(deletionObjects.values()).filter(object =>
            isDevclass(object) && normalize(object.objName).startsWith('$'));
        const objectsToTransport = Array.from(deletionObjects.values()).filter(object =>
            !temporaryPackages.includes(object));
        // Cleanup exports the previous installation's objects, regardless of the new namespace.
        const needsStaging = normalize(installed.getDevclass() || '').startsWith('$');
        const stagingDevclasses: string[] = [];
        let retainedOriginalTadir: TADIR[] = [];
        if (needsStaging && (objectsToTransport.length > 0 || retainedTables.length > 0)) {
            const existingObjects = await SystemConnector.getExistingObjects(
                [...objectsToTransport, ...retainedTables].map(object => ({
                    pgmid: object.pgmid, object: object.object, objName: object.objName, devclass: ''
                }))
            );
            // SAP only accepts objects of a custom namespace in packages of that namespace:
            // stage them by namespace.
            const stagingGroups = new Map<string, TADIR[]>();
            for (const object of existingObjects) {
                const namespace = getCustomNamespace(object.objName) || '';
                stagingGroups.set(namespace, [...(stagingGroups.get(namespace) || []), object]);
            }
            context.revert.cleanupOriginalTadir = [];
            for (const [namespace, objects] of stagingGroups) {
                if (namespace) {
                    await importStagingNamespace(context, namespace);
                }
                const stagingDevclass = await createStagingPackage(context, namespace);
                stagingDevclasses.push(stagingDevclass);
                for (const object of objects) {
                    context.revert.cleanupOriginalTadir.push({ ...object });
                    if (retainedKeys.has(objectKey(object))) {
                        retainedOriginalTadir.push({ ...object });
                    }
                    await SystemConnector.tadirInterface({ ...object, devclass: stagingDevclass, srcsystem: 'TRM' });
                }
            }
        }
        if (retainedTables.length > 0) {
            await backupRetainedTables(context, retainedTables);
            // Retained tables stay installed: move them out of the staging package before it is deleted.
            await restoreTadirAssignments(retainedOriginalTadir);
        }
        if (objectsToTransport.length > 0) {
            await dummy.addObjects(objectsToTransport, false);
        }
        if (stagingDevclasses.length > 0) {
            await dummy.addObjects(stagingDevclasses.map(devclass => ({ pgmid: 'R3TR', object: 'DEVC', objName: devclass })), false);
        }
        // Namespaces imported for the staging go with their staging packages.
        const temporaryNamespaces = (context.revert.temporaryNamespaces || [])
            .filter(namespace => !namespacesToDelete.some(o => normalize(o) === normalize(namespace)));
        if (temporaryNamespaces.length > 0) {
            await dummy.addObjects(temporaryNamespaces.map(namespace => ({ pgmid: 'R3TR', object: 'NSPC', objName: namespace })), false);
        }
        // The copy keeps the E071K keys and OBJFUNC K: the release exports the current rows
        // (restored by a rollback) and the registry turns them into deletions by key.
        context.revert.cleanupCustomizingSources = [];
        for (const trkorr of customizingSources) {
            Logger.loading(`Including customizing from transport ${trkorr}...`, true);
            await dummy.addObjectsFromTransport(trkorr);
            context.revert.cleanupCustomizingSources.push(trkorr);
        }
        const packageDepth = (devclass: string): number => {
            const visited = new Set<string>();
            let parent = packageParents.get(normalize(devclass));
            while (parent && !visited.has(parent)) {
                visited.add(parent);
                parent = packageParents.get(parent);
            }
            return visited.size;
        };
        // Delete descendants before their parents, regardless of transport entry order.
        temporaryPackages.sort((a, b) => packageDepth(b.objName) - packageDepth(a.objName));
        context.revert.cleanupTemporaryPackages = [];
        // Snapshot every definition before deleting any package, including for partial failures.
        for (const devclass of temporaryPackages) {
            const pkg = await SystemConnector.getDevclass(devclass.objName);
            if (!pkg) {
                throw new Error(`Cannot back up temporary SAP package ${devclass.objName}`);
            }
            context.revert.cleanupTemporaryPackages.push({ ...pkg });
        }
        try {
            await deleteTemporaryCleanupPackages(temporaryPackages);
        } catch (e) {
            // Their objects are already in the deletion transport: an empty local package is a harmless leftover.
            Logger.warning(`Could not delete local SAP package(s) ${temporaryPackages.map(o => o.objName).join(', ')} (${e instanceof Error ? e.message : String(e)}): delete them manually.`, { important: true });
        }

        //guard: clean and rebuild comments
        await dummy.removeComments();
        await dummy.addComment(`name=${installed.manifest.get().name}`);
        await dummy.addComment(`version=${installed.manifest.get().version}`);

        try {
            await releaseDeletionTransport(dummy, context.rawInput.packageData.registry, context);
        } catch (e) {
            if (!(e instanceof RegistryDeletionTransportUnavailableError)) {
                throw e;
            }
            //at this point the dummy is already released, transport cannot be deleted but it's a harmless release of a transport of copies.
            await restoreCleanupAssignments(context, true);
            if (target.requireDeletion) {
                Logger.error(e.message, { important: true });
                throw e;
            }
            Logger.warning(`${e.message} Manual cleanup of previous release install might be necessary.`, { important: true });
            // Deleting the staging packages needs a deletion transport too.
            if (stagingDevclasses.length > 0) {
                Logger.warning(`SAP package(s) ${stagingDevclasses.join(', ')}, created for the cleanup, were left on ${SystemConnector.getDest()}: delete them manually.`, { important: true });
            }
            if (context.revert.temporaryNamespaces?.length > 0) {
                Logger.warning(`Namespace(s) ${context.revert.temporaryNamespaces.join(', ')}, imported for the cleanup, were left on ${SystemConnector.getDest()}: delete them manually.`, { important: true });
            }
        }
    });
}

/**
 * Whether the deletion transport generated by {@link cleanupInstalledPackage} must be carried
 * through the landscape. Objects of a temporary (`$`) installation only exist on this system.
 */
export function isDeletionForwardable(context: PackageCleanupContext): boolean {
    return !!context.revert.dele && !normalize(context.runtime.update?.getDevclass() || '').startsWith('$');
}

/**
 * Adds the deletion transport to the import queue of the landscape target system, so the
 * removed objects are also deleted there.
 * For a clean landscape, it has to be imported before any transport of a later release.
 */
export async function forwardDeletionTransport(context: PackageCleanupContext, targetSystem: string): Promise<void> {
    // The queue may be changed even when the connector response fails.
    context.revert.deleInTargetTms = true;
    await SystemConnector.forwardTransport(context.revert.dele.trkorr, targetSystem, SystemConnector.getDest(), true);
}

/**
 * Removes a transport from the import queue of `targetSystem`. Only the queue of the connected
 * system can be changed: another system's queue would need its credentials, so the operator is
 * warned to remove it manually. Returns whether the transport was removed.
 */
export async function removeFromImportQueue(trkorr: string, targetSystem: string, description: string): Promise<boolean> {
    if (normalize(targetSystem) === normalize(SystemConnector.getDest())) {
        await SystemConnector.deleteTmsTransport(trkorr, targetSystem);
        return true;
    }
    Logger.warning(`${description} ${trkorr} may be in the ${targetSystem} import queue: remove it manually in STMS (it can't be removed from ${SystemConnector.getDest()}).`, { important: true });
    return false;
}

/** Removes the deletion transport from the target system import queue, when it was forwarded. */
export async function revertForwardedDeletionTransport(context: PackageCleanupContext, targetSystem: string): Promise<void> {
    if (context.revert.deleInTargetTms) {
        await removeFromImportQueue(context.revert.dele.trkorr, targetSystem, `Deletion transport`);
    }
}

/**
 * Rolls back {@link cleanupInstalledPackage}: recreates deleted temporary packages, deletes the
 * deletion transport or, once its import started, re-imports the copy of the deleted objects,
 * restores retained tables, and restores object assignments.
 * With `restore` set to `false` (a later destructive cleanup failed), previous state is not
 * restored over objects that were not deleted: only the unreleased transports are deleted.
 * Every independent operation is attempted; the first failure is thrown afterwards.
 */
export async function revertInstalledPackageCleanup(context: PackageCleanupContext, restore = true): Promise<void> {
    let firstError: unknown;
    if (restore) {
        try {
            await restoreCleanupPackages(context);
        } catch (error) {
            firstError = error;
        }
    }
    try {
        if (context.revert.dele) {
            //check if it can be deleted -> the exception might have been raised before the transport release, we can still cleanup nicely
            const transport = new Transport(context.revert.dele.trkorr);
            if (await (transport.canBeDeleted())) {
                await transport.delete();
            } else if (context.revert.deleImportStarted) {
                if (restore) {
                    await restoreTransport(context.revert.dele);
                } else {
                    Logger.warning(`Objects deleted by ${context.revert.dele.trkorr} were not restored, as the cleanup of the imported objects failed: manual restore might be necessary.`, { important: true });
                }
            } else {
                // Released but never imported: the objects were not deleted, re-importing the copy would overwrite them.
                Logger.log(`Deletion transport ${context.revert.dele.trkorr} was not imported, objects restore skipped`, true);
            }
        } else if (context.revert.updateCleanupTransport
            && await context.revert.updateCleanupTransport.canBeDeleted()) {
            await context.revert.updateCleanupTransport.delete();
        }
    } catch (error) {
        firstError ||= error;
    }
    try {
        if (context.revert.retainedTables) {
            if (restore) {
                // Old table definitions are imported over the new ones: data is kept.
                await restoreTransport(context.revert.retainedTables);
            } else {
                Logger.warning(`Retained tables backup ${context.revert.retainedTables.trkorr} was not restored, as the cleanup of the imported objects failed: manual restore might be necessary.`, { important: true });
            }
        } else if (context.revert.updateTablesBackupTransport
            && await context.revert.updateTablesBackupTransport.canBeDeleted()) {
            await context.revert.updateTablesBackupTransport.delete();
        }
    } catch (error) {
        firstError ||= error;
    }
    if (restore) {
        try {
            await restoreCleanupAssignments(context, false);
        } catch (error) {
            firstError ||= error;
        }
    }
    if (firstError) {
        throw firstError;
    }
}
