import { Inquirer, Logger } from "trm-commons";
import { InstallTransport, SystemConnector } from "../../../systemConnector";
import { Transport, TrmTransportIdentifier } from "../../../transport";
import { TransportBinary, TrmPackage } from "../../../trmPackage";
import { AbstractRegistry, RegistryDeletionTransportUnauthorizedError } from "../../../registry";
import { packageDataFromTdevc, getPackageNamespace } from "../../../commons";
import { DEVCLASS, E071, TADIR, TDEVC } from "../../../client";
import { randomBytes } from "crypto";
import type { InstallPackageReplacements } from "../../install";
import { releaseDeletionTransport } from "./releaseDeletionTransport";
import { restoreTransport } from "./restoreTransport";
import { withScopedPrefix } from "./withScopedPrefix";
import { ActionLockScope, objectLockResource } from "./actionLocks";

type CleanupObject = Pick<E071, 'pgmid' | 'object' | 'objName'>;

/** Rollback state written while removing the objects of an installed release. */
export interface PackageCleanupRevert {
    /** SAP packages generated by the action; the cleanup adds its staging package here. */
    sapPackages: DEVCLASS[],
    dele?: TransportBinary,
    /** Set before the deletion transport import: only then the objects must be restored from `dele`. */
    deleImportStarted?: boolean,
    cleanupOriginalTadir?: TADIR[],
    cleanupTemporaryPackages?: TDEVC[],
    updateCleanupTransport?: Transport,
    updateTablesBackupTransport?: Transport,
    retainedTables?: TransportBinary,
    /** Customizing transports whose rows were added to the deletion transport. */
    cleanupCustomizingSources?: string[],
    /** Set before forwarding the deletion transport, as the TMS queue may change even when the call fails. */
    deleInTargetTms?: boolean
}

/** Minimum workflow context needed to remove an installed release from the target system. */
export interface PackageCleanupContext {
    lockScope?: ActionLockScope,
    rawInput: {
        packageData: {
            name: string,
            registry: AbstractRegistry
        },
        contextData?: {
            noInquirer?: boolean,
            /** Packages installed on the target system: SAP packages of other installations are never cleaned up. */
            systemPackages?: TrmPackage[]
        }
    },
    runtime?: {
        /** Installed release whose objects are removed. */
        update: TrmPackage,
        /** Install package mappings recorded for the installed release. */
        previousInstallPackages: InstallPackageReplacements[],
        /** Transports recorded for the installed release; its customizing comes from the `CUST` ones. */
        previousInstallTransports?: InstallTransport[],
        dele?: Transport
    },
    revert?: PackageCleanupRevert
}

/** What remains on the system once the cleanup is complete. */
export type PackageCleanupTarget = {
    /** Objects shipped by the incoming release. Empty when uninstalling. */
    incomingObjects: TADIR[],
    /** SAP packages that hold the incoming release. Empty when uninstalling. */
    keptDevclasses: string[],
    /** Logger/Inquirer prefix shown while the cleanup runs. */
    prefix: string,
    /** Action name used in abort messages, e.g. `Update`. */
    actionName: string,
    /**
     * When `true`, an unauthorized deletion transport request is rethrown after restoring
     * object assignments. Otherwise it only logs a manual cleanup warning.
     */
    requireDeletion: boolean,
    /**
     * When `true`, the customizing rows shipped by the installed release are kept.
     * Otherwise they are always deleted, without asking.
     */
    keepCustomizing?: boolean
}

function normalize(value: string): string {
    return value.trim().toUpperCase();
}

function objectKey(object: CleanupObject): string {
    return `${normalize(object.pgmid)}\u0000${normalize(object.object)}\u0000${normalize(object.objName)}`;
}

function isDevclass(object: CleanupObject): boolean {
    return normalize(object.pgmid) === 'R3TR' && normalize(object.object) === 'DEVC';
}

function isNamespace(object: CleanupObject): boolean {
    return normalize(object.pgmid) === 'R3TR' && normalize(object.object) === 'NSPC';
}

/** Custom (`/XXX/`) namespace of a SAP package, if any. */
function getCustomNamespace(devclass: string): string | undefined {
    try {
        const namespace = getPackageNamespace(devclass);
        return namespace.startsWith('/') ? namespace : undefined;
    } catch (e) {
        // devclass doesn't use a custom namespace
        return undefined;
    }
}

/**
 * TRM packages, other than `installed`, installed in one of `devclasses` (normalized SAP package
 * names, usually the live subtree of the installed release).
 */
export function getPackagesInstalledIn(systemPackages: TrmPackage[], installed: TrmPackage, devclasses: Set<string>): TrmPackage[] {
    const installedDevclass = normalize(installed.getDevclass() || '');
    return systemPackages.filter(pkg => {
        const devclass = normalize(pkg.getDevclass() || '');
        return devclass && devclass !== installedDevclass && devclasses.has(devclass);
    });
}

/** Deletes every temporary package, reporting the first failure after the cleanup pass. */
export async function deleteTemporaryCleanupPackages(
    temporaryPackages: Array<Pick<E071, 'objName'>>
): Promise<void> {
    let firstError: unknown;
    for (const devclass of temporaryPackages) {
        try {
            await SystemConnector.deleteTemporaryPackage(devclass.objName);
        } catch (error) {
            firstError ||= error;
        }
    }
    if (firstError) {
        throw firstError;
    }
}

async function restoreCleanupPackages(context: PackageCleanupContext): Promise<void> {
    // Snapshots are stored in deletion order: reverse it to recreate parents first.
    let firstError: unknown;
    for (const pkg of [...(context.revert.cleanupTemporaryPackages || [])].reverse()) {
        try {
            if (await SystemConnector.getDevclass(pkg.devclass)) {
                continue;
            }
            await SystemConnector.createPackage({
                ...packageDataFromTdevc(pkg, {
                    devclass: pkg.devclass,
                    ctext: pkg.ctext || '',
                    as4user: pkg.as4user || SystemConnector.getLogonUser(),
                    dlvunit: pkg.dlvunit,
                    pdevclass: pkg.pdevclass || ''
                }),
                parentcl: pkg.parentcl,
                tpclass: pkg.tpclass
            });
        } catch (error) {
            firstError ||= error;
        }
    }
    if (firstError) {
        throw firstError;
    }
}

async function restoreCleanupAssignments(context: PackageCleanupContext, restorePackages: boolean): Promise<void> {
    if (restorePackages) {
        await restoreCleanupPackages(context);
    }
    await restoreTadirAssignments(context.revert.cleanupOriginalTadir || []);
}

async function restoreTadirAssignments(originals: TADIR[]): Promise<void> {
    if (originals.length === 0) {
        return;
    }
    const existing = new Set((await SystemConnector.getExistingObjects(originals)).map(objectKey));
    let firstError: unknown;
    for (const object of originals) {
        if (existing.has(objectKey(object))) {
            try {
                await SystemConnector.tadirInterface(object);
            } catch (error) {
                firstError ||= error;
            }
        }
    }
    if (firstError) {
        throw firstError;
    }
}

/**
 * Releases a transport of copies with the previous definition of the retained tables,
 * so a rollback can restore them without dropping their data.
 */
async function backupRetainedTables(
    context: PackageCleanupContext,
    retainedTables: CleanupObject[]
): Promise<void> {
    Logger.loading(`Backing up ${retainedTables.length} retained tables...`, true);
    const backup = await Transport.createToc({
        text: `@X1@TRM (BKP) ${context.rawInput.packageData.name} ${context.runtime.update.manifest.get().version}`,
        target: SystemConnector.getDest()
    });
    context.revert.updateTablesBackupTransport = backup;
    await backup.addObjects(retainedTables.map(object => ({
        pgmid: object.pgmid,
        object: object.object,
        objName: object.objName
    })), false);
    await backup.release(false, true);
    context.revert.retainedTables = {
        trkorr: backup.trkorr,
        entries: undefined,
        binaries: (await backup.download()).binaries
    };
}

/**
 * Customizing transports of the installed release whose rows must be deleted. Only transports
 * recorded at install time and still on the system count.
 */
async function getCustomizingSources(context: PackageCleanupContext, target: PackageCleanupTarget): Promise<string[]> {
    const sources: string[] = [];
    for (const transport of context.runtime.previousInstallTransports || []) {
        if (normalize(transport.trmType || '') !== TrmTransportIdentifier.CUST) {
            continue;
        }
        if (await new Transport(transport.trkorr).getE070()) {
            sources.push(transport.trkorr);
        } else {
            Logger.warning(`Customizing transport ${transport.trkorr} is no longer on ${SystemConnector.getDest()}: its rows can't be deleted.`);
        }
    }
    if (sources.length === 0) {
        return [];
    }
    if (target.keepCustomizing) {
        Logger.warning(`Keeping customizing of ${sources.length} transports (${sources.join(', ')}).`);
        return [];
    }
    return sources;
}

/**
 * Removes the objects of the installed release (`context.runtime.update`) that are not part
 * of `target`, through a deletion transport generated by the registry.
 *
 * Shared by upgrades, where the target is the incoming release, and by uninstalls, where the
 * target is empty. It also removes SAP packages left empty, locally added objects (after
 * confirmation), the package namespace when no other package uses it, and the customizing rows
 * of the installed release. Tables shipped again by the target are kept and
 * backed up so a rollback preserves their data.
 */
export async function cleanupInstalledPackage(context: PackageCleanupContext, target: PackageCleanupTarget): Promise<void> {
    await withScopedPrefix(target.prefix, async () => {
        const installed = context.runtime.update;
        //1- generate dummy transport
        Logger.loading(`Generating transport...`);
        const dummy = await Transport.createToc({
            text: `@X1@TRM (DELE) ${context.rawInput.packageData.name} ${installed.manifest.get().version}`,
            target: SystemConnector.getDest()
        });
        context.revert.updateCleanupTransport = dummy;
        const installedTransportObjects = installed.getTransport()
            ? await installed.getTransport().getE071()
            : [];
        // Table content (entries with E071K keys, e.g. a landscape transport carrying the CUST
        // transports) is deleted by key through the customizing transports below. Added without
        // its keys, it would request the deletion of the whole table object.
        const keyedObjects = new Set(installed.getTransport() && installedTransportObjects.length > 0
            ? (await installed.getTransport().getE071K()).map(objectKey)
            : []);
        // A namespace may be used by packages outside this installation: it's only deleted
        // through the usage check below, never because the installed transport carries it.
        const previousNamespaces = installedTransportObjects.filter(object => !keyedObjects.has(objectKey(object)) && isNamespace(object));
        const previousTransportObjects = installedTransportObjects.filter(object => !keyedObjects.has(objectKey(object)) && !isNamespace(object));
        const incomingObjects = target.incomingObjects;
        // Tables shipped again by the new release are adjusted by its import instead of
        // being dropped and re-created, which would lose their data.
        const incomingKeys = new Set(incomingObjects.map(objectKey));
        const retainedTables = previousTransportObjects.filter(object =>
            normalize(object.pgmid) === 'R3TR' && normalize(object.object) === 'TABL'
            && incomingKeys.has(objectKey(object)));
        const retainedKeys = new Set(retainedTables.map(objectKey));
        retainedTables.forEach(object => Logger.log(`Keeping table ${object.objName} (present in new release)`, true));
        const currentDevclasses = new Set(target.keptDevclasses.map(normalize));
        const previousDevclasses = new Map<string, string>();
        context.runtime.previousInstallPackages.forEach(replacement => {
            previousDevclasses.set(normalize(replacement.installDevclass), replacement.installDevclass);
        });
        // Older installations that kept the publisher package names have no replacement rows.
        if (previousDevclasses.size === 0 && installed.getDevclass()) {
            const previousRoot = installed.getDevclass();
            previousDevclasses.set(normalize(previousRoot), previousRoot);
        }
        previousTransportObjects.forEach(object => {
            if (isDevclass(object)) {
                previousDevclasses.set(normalize(object.objName), object.objName);
            }
        });
        const installedDevclasses = new Set(previousDevclasses.keys());
        const generatedDevclasses = new Set(context.revert.sapPackages.map(normalize));

        // Installation mappings do not include subpackages created locally afterwards.
        // Inspect the live hierarchy even when the installation keeps its root package.
        const packageParents = new Map<string, string>();
        for (const devclass of Array.from(previousDevclasses.values())) {
            for (const subpackage of await SystemConnector.getSubpackages(devclass)) {
                const key = normalize(subpackage.devclass);
                previousDevclasses.set(key, subpackage.devclass);
                if (subpackage.parentcl) {
                    packageParents.set(key, normalize(subpackage.parentcl));
                }
            }
        }

        // Other TRM packages installed underneath have their own lifecycle and are ignored: the delete
        // action deletes them first, an upgrade removes everything else. Their ancestors stay as packages.
        const otherInstallations = new Map(getPackagesInstalledIn(
            context.rawInput.contextData?.systemPackages || [], installed, new Set(previousDevclasses.keys())
        ).map(pkg => [normalize(pkg.getDevclass()), pkg]));
        const isOtherInstallation = (devclass: string): boolean => {
            const visited = new Set<string>();
            let current = normalize(devclass);
            while (current && !visited.has(current)) {
                if (otherInstallations.has(current)) {
                    return true;
                }
                visited.add(current);
                current = packageParents.get(current);
            }
            return false;
        };
        otherInstallations.forEach(pkg => Logger.log(`Ignoring SAP package ${pkg.getDevclass()}: TRM package ${pkg.packageName} is installed there`, true));

        // Local additions remain cleanup candidates even when reused as incoming targets.
        // The first local package owns the decision for its locally added descendants.
        const cleanupGroups = new Map<string, Set<string>>();
        for (const normalizedDevclass of previousDevclasses.keys()) {
            const locallyAdded = !installedDevclasses.has(normalizedDevclass);
            if (generatedDevclasses.has(normalizedDevclass) || (!locallyAdded && currentDevclasses.has(normalizedDevclass))
                || isOtherInstallation(normalizedDevclass)) {
                continue;
            }
            let root = normalizedDevclass;
            const visited = new Set([root]);
            let parent = packageParents.get(root);
            while (parent && previousDevclasses.has(parent) && !generatedDevclasses.has(parent)
                && (!installedDevclasses.has(parent) === locallyAdded)
                && (locallyAdded || !currentDevclasses.has(parent)) && !visited.has(parent)) {
                root = parent;
                visited.add(root);
                parent = packageParents.get(root);
            }
            if (!cleanupGroups.has(root)) {
                cleanupGroups.set(root, new Set());
            }
            cleanupGroups.get(root).add(normalizedDevclass);
        }

        const changedDevclassesToDelete: string[] = [];
        const extraObjectsToDelete = new Map<string, CleanupObject>();
        for (const [root, group] of cleanupGroups) {
            const devclass = previousDevclasses.get(root);

            // Only objects outside both releases need an extra cleanup decision.
            const objectsAfterImport = new Map<string, TADIR>();
            for (const member of group) {
                for (const object of await SystemConnector.getDevclassObjects(previousDevclasses.get(member), false)) {
                    // Package definitions follow the decision for the whole subtree; namespaces the usage check.
                    if (!isDevclass(object) && !isNamespace(object)) {
                        objectsAfterImport.set(objectKey(object), object);
                    }
                }
            }
            previousTransportObjects.forEach(object => objectsAfterImport.delete(objectKey(object)));
            incomingObjects.forEach(object => {
                objectsAfterImport.delete(objectKey(object));
            });

            // Every locally added package definition is an extra object, including
            // the root of this cleanup group, regardless of whether it has contents.
            const packagesToRemove = Array.from(group).filter(member => !currentDevclasses.has(member));
            const extraObjectCount = objectsAfterImport.size + packagesToRemove.filter(member => !installedDevclasses.has(member)).length;
            if (extraObjectCount > 0) {
                const extraObjectsMessage = `Cleanup of SAP package ${devclass}${group.size > 1 ? ' and its subpackages' : ''} will delete ${extraObjectCount} extra objects outside this installation`;
                if (context.rawInput.contextData.noInquirer) {
                    Logger.warning(`${extraObjectsMessage}.`);
                }
                const { deleteExtraObjects } = context.rawInput.contextData.noInquirer
                    ? { deleteExtraObjects: true }
                    : await Inquirer.prompt({
                        name: 'deleteExtraObjects',
                        type: 'confirm',
                        message: `${extraObjectsMessage}. Continue?`,
                        default: true
                    });
                if (!deleteExtraObjects) {
                    continue;
                }
                objectsAfterImport.forEach((object, key) => extraObjectsToDelete.set(key, {
                    pgmid: object.pgmid,
                    object: object.object,
                    objName: object.objName
                }));
            }
            changedDevclassesToDelete.push(...packagesToRemove.map(member => previousDevclasses.get(member)));
        }

        // A retained child still needs its ancestors, including when cleanup was declined.
        const deletableDevclasses = new Set(changedDevclassesToDelete.map(normalize));
        for (const devclass of previousDevclasses.keys()) {
            if (deletableDevclasses.has(devclass)) {
                continue;
            }
            const visited = new Set<string>();
            let parent = packageParents.get(devclass);
            while (parent && !visited.has(parent)) {
                visited.add(parent);
                deletableDevclasses.delete(parent);
                parent = packageParents.get(parent);
            }
        }
        const packagesToDelete = changedDevclassesToDelete.filter(devclass => deletableDevclasses.has(normalize(devclass)));

        // A namespace can only be cleaned up alongside its last remaining package: any other SAP
        // package in it (TDEVC NAMESPACE), installed by TRM or not, keeps it. Namespaces of the
        // incoming release are kept, as its packages may not have been imported yet.
        const incomingNamespaces = new Set(target.keptDevclasses.map(getCustomNamespace).filter(Boolean).map(normalize));
        const namespaceCandidates = new Map<string, string>();
        previousNamespaces.forEach(object => namespaceCandidates.set(normalize(object.objName), object.objName));
        const rootNamespace = installed.getDevclass() ? getCustomNamespace(installed.getDevclass()) : undefined;
        if (rootNamespace) {
            namespaceCandidates.set(normalize(rootNamespace), rootNamespace);
        }
        const deletingDevclasses = new Set(packagesToDelete.map(normalize));
        const namespacesToDelete: string[] = [];
        for (const [key, namespace] of namespaceCandidates) {
            if (incomingNamespaces.has(key)) {
                Logger.log(`Keeping namespace ${namespace}: used by the incoming release`, true);
                continue;
            }
            try {
                if (!(await SystemConnector.getNamespace(namespace))) {
                    continue;
                }
                const remainingPackages = (await SystemConnector.getNamespacePackages(namespace))
                    .filter(pkg => !deletingDevclasses.has(normalize(pkg.devclass)));
                if (remainingPackages.length === 0) {
                    namespacesToDelete.push(namespace);
                } else {
                    Logger.log(`Keeping namespace ${namespace}: still used by SAP packages ${remainingPackages.map(pkg => pkg.devclass).join(', ')}`, true);
                }
            } catch (e) {
                Logger.warning(`Keeping namespace ${namespace}: its usage could not be checked (${String(e)})`);
            }
        }

        // Installed objects moved to a package outside this installation (customer development)
        // are kept unless confirmed; those now in another TRM package belong to it and are kept.
        const relocatedObjects = (await SystemConnector.getExistingObjects(previousTransportObjects
            .filter(object => normalize(object.pgmid) === 'R3TR' && !isDevclass(object) && !retainedKeys.has(objectKey(object)))
            .map(object => ({ pgmid: object.pgmid, object: object.object, objName: object.objName, devclass: '' }))))
            .filter(object => object.devclass && (!previousDevclasses.has(normalize(object.devclass)) || isOtherInstallation(object.devclass)));
        const movedKeys = new Set<string>();
        const movedObjects = relocatedObjects.filter(object => {
            if (!isOtherInstallation(object.devclass)) {
                return true;
            }
            Logger.log(`Keeping ${object.pgmid} ${object.object} ${object.objName}: it's in SAP package ${object.devclass} of another TRM package`, true);
            movedKeys.add(objectKey(object));
            return false;
        });
        if (movedObjects.length > 0) {
            movedObjects.forEach(object => Logger.warning(`${object.pgmid} ${object.object} ${object.objName} was moved to SAP package ${object.devclass}, outside this installation`));
            const { deleteMovedObjects } = context.rawInput.contextData.noInquirer
                ? { deleteMovedObjects: false }
                : await Inquirer.prompt({
                    name: 'deleteMovedObjects',
                    type: 'confirm',
                    message: `Delete ${movedObjects.length} installed objects moved outside this installation too?`,
                    default: false
                });
            if (!deleteMovedObjects) {
                movedObjects.forEach(object => movedKeys.add(objectKey(object)));
                Logger.warning(`Keeping ${movedObjects.length} objects moved outside this installation.`);
            }
        }

        const customizingSources = await getCustomizingSources(context, target);

        const additionalObjects = [...extraObjectsToDelete.values(), ...packagesToDelete.map(devclass => ({
            pgmid: 'R3TR',
            object: 'DEVC',
            objName: devclass
        })), ...namespacesToDelete.map(namespace => ({
            pgmid: 'R3TR',
            object: 'NSPC',
            objName: namespace
        }))];
        // Validate the complete deletion selection before adding anything to the transport.
        const deletionObjects = new Map([...previousTransportObjects, ...additionalObjects]
            .filter(object => !retainedKeys.has(objectKey(object)) && !movedKeys.has(objectKey(object)))
            .map(object => [objectKey(object), object]));
        // TRM comment rows of the installed transport are not objects to delete.
        const hasObjectsToDelete = Array.from(deletionObjects.values()).some(object => normalize(object.pgmid) !== '*');
        if (!hasObjectsToDelete && retainedTables.length === 0 && customizingSources.length === 0) {
            Logger.warning(`Nothing to delete for package ${context.rawInput.packageData.name}: deletion transport was not generated. Manual cleanup of previous release install might be necessary.`);
            try {
                if (await dummy.canBeDeleted()) {
                    await dummy.delete();
                    context.revert.updateCleanupTransport = undefined;
                }
            } catch (e) {
                Logger.warning(`Could not delete transport ${dummy.trkorr}: ${String(e)}`);
            }
            return;
        }
        await context.lockScope.acquire([
            ...Array.from(deletionObjects.values(), objectLockResource),
            ...Array.from(deletionObjects.values())
                .filter(isDevclass)
                .map(object => ({ type: "DEVCLASS" as const, name: object.objName }))
        ]);
        if (deletionObjects.size > 0) {
            Logger.loading(`Checking cleanup objects locks...`, true);
            const locks = await SystemConnector.getObjectsLocks(Array.from(deletionObjects.values(), object => ({
                PGMID: object.pgmid,
                OBJECT: object.object,
                OBJ_NAME: object.objName
            })));
            if (locks.length > 0) {
                locks.forEach(lock => Logger.error(`${lock.pgmid} ${lock.object} ${lock.objName} is currently locked in transport ${lock.trkorr}`));
                throw new Error(`${target.actionName} aborted. To continue, all cleanup objects and SAP packages must be released`);
            }
        }
        const temporaryPackages = Array.from(deletionObjects.values()).filter(object =>
            isDevclass(object) && normalize(object.objName).startsWith('$'));
        const objectsToTransport = Array.from(deletionObjects.values()).filter(object =>
            !temporaryPackages.includes(object));
        // Cleanup exports the previous installation's objects, regardless of the new namespace.
        const needsStaging = normalize(installed.getDevclass() || '').startsWith('$');
        let stagingDevclass: string;
        let retainedOriginalTadir: TADIR[] = [];
        if (needsStaging && (objectsToTransport.length > 0 || retainedTables.length > 0)) {
            // A short-lived, transportable package lets CTS export local objects.
            do {
                stagingDevclass = `ZTRM_DELE_${randomBytes(8).toString('hex').toUpperCase()}`; // 25 characters; DEVCLASS allows 30.
            } while (await SystemConnector.getDevclass(stagingDevclass));
            Logger.loading(`Creating package ${stagingDevclass}...`, true);
            // Track before the mutating await because SAP may commit the package
            // even when the connector response fails.
            context.revert.sapPackages.push(stagingDevclass);
            await SystemConnector.createPackage({
                devclass: stagingDevclass,
                ctext: 'TRM upgrade cleanup',
                as4user: SystemConnector.getLogonUser(),
                dlvunit: 'HOME',
                pdevclass: await SystemConnector.getDefaultTransportLayer()
            });
            await SystemConnector.tadirInterface({
                pgmid: 'R3TR', object: 'DEVC', objName: stagingDevclass,
                devclass: stagingDevclass, srcsystem: 'TRM'
            });
            const existingObjects = await SystemConnector.getExistingObjects(
                [...objectsToTransport, ...retainedTables].map(object => ({
                    pgmid: object.pgmid, object: object.object, objName: object.objName, devclass: ''
                }))
            );
            context.revert.cleanupOriginalTadir = [];
            for (const object of existingObjects) {
                context.revert.cleanupOriginalTadir.push({ ...object });
                if (retainedKeys.has(objectKey(object))) {
                    retainedOriginalTadir.push({ ...object });
                }
                await SystemConnector.tadirInterface({ ...object, devclass: stagingDevclass, srcsystem: 'TRM' });
            }
        }
        if (retainedTables.length > 0) {
            await backupRetainedTables(context, retainedTables);
            // Retained tables stay installed: move them out of the staging package before it is deleted.
            await restoreTadirAssignments(retainedOriginalTadir);
        }
        if (objectsToTransport.length > 0) {
            await dummy.addObjects(objectsToTransport, false);
        }
        if (stagingDevclass) {
            await dummy.addObjects([
                { pgmid: 'R3TR', object: 'DEVC', objName: stagingDevclass }
            ], false);
        }
        // The copy keeps the E071K keys and OBJFUNC K: the release exports the current rows
        // (restored by a rollback) and the registry turns them into deletions by key.
        context.revert.cleanupCustomizingSources = [];
        for (const trkorr of customizingSources) {
            Logger.loading(`Including customizing from transport ${trkorr}...`, true);
            await dummy.addObjectsFromTransport(trkorr);
            context.revert.cleanupCustomizingSources.push(trkorr);
        }
        const packageDepth = (devclass: string): number => {
            const visited = new Set<string>();
            let parent = packageParents.get(normalize(devclass));
            while (parent && !visited.has(parent)) {
                visited.add(parent);
                parent = packageParents.get(parent);
            }
            return visited.size;
        };
        // Delete descendants before their parents, regardless of transport entry order.
        temporaryPackages.sort((a, b) => packageDepth(b.objName) - packageDepth(a.objName));
        context.revert.cleanupTemporaryPackages = [];
        // Snapshot every definition before deleting any package, including for partial failures.
        for (const devclass of temporaryPackages) {
            const pkg = await SystemConnector.getDevclass(devclass.objName);
            if (!pkg) {
                throw new Error(`Cannot back up temporary SAP package ${devclass.objName}`);
            }
            context.revert.cleanupTemporaryPackages.push({ ...pkg });
        }
        await deleteTemporaryCleanupPackages(temporaryPackages);

        //guard: clean and rebuild comments
        await dummy.removeComments();
        await dummy.addComment(`name=${installed.manifest.get().name}`);
        await dummy.addComment(`version=${installed.manifest.get().version}`);

        try {
            await releaseDeletionTransport(dummy, context.rawInput.packageData.registry, context);
        } catch (e) {
            if (!(e instanceof RegistryDeletionTransportUnauthorizedError)) {
                throw e;
            }
            //at this point the dummy is already released, transport cannot be deleted but it's a harmless release of a transport of copies.
            await restoreCleanupAssignments(context, true);
            if (target.requireDeletion) {
                Logger.error(`User is not authorized to generate deletion transports.`);
                throw e;
            }
            Logger.warning(`User is not authorized to generate cleanup transports. Manual cleanup of previous release install might be necessary.`);
        }
    });
}

/**
 * Whether the deletion transport generated by {@link cleanupInstalledPackage} must be carried
 * through the landscape. Objects of a temporary (`$`) installation only exist on this system.
 */
export function isDeletionForwardable(context: PackageCleanupContext): boolean {
    return !!context.revert.dele && !normalize(context.runtime.update?.getDevclass() || '').startsWith('$');
}

/**
 * Adds the deletion transport to the import queue of the landscape target system, so the
 * removed objects are also deleted there.
 * For a clean landscape, it has to be imported before any transport of a later release.
 */
export async function forwardDeletionTransport(context: PackageCleanupContext, targetSystem: string): Promise<void> {
    // The queue may be changed even when the connector response fails.
    context.revert.deleInTargetTms = true;
    await SystemConnector.forwardTransport(context.revert.dele.trkorr, targetSystem, SystemConnector.getDest(), true);
}

/** Removes the deletion transport from the target system import queue, when it was forwarded. */
export async function revertForwardedDeletionTransport(context: PackageCleanupContext, targetSystem: string): Promise<void> {
    if (context.revert.deleInTargetTms) {
        await SystemConnector.deleteTmsTransport(context.revert.dele.trkorr, targetSystem);
    }
}

/**
 * Rolls back {@link cleanupInstalledPackage}: recreates deleted temporary packages, deletes the
 * deletion transport or, once its import started, re-imports the copy of the deleted objects,
 * restores retained tables, and restores object assignments.
 * Every independent operation is attempted; the first failure is thrown afterwards.
 */
export async function revertInstalledPackageCleanup(context: PackageCleanupContext): Promise<void> {
    let firstError: unknown;
    try {
        await restoreCleanupPackages(context);
    } catch (error) {
        firstError = error;
    }
    try {
        if (context.revert.dele) {
            //check if it can be deleted -> the exception might have been raised before the transport release, we can still cleanup nicely
            const transport = new Transport(context.revert.dele.trkorr);
            if (await (transport.canBeDeleted())) {
                await transport.delete();
            } else if (context.revert.deleImportStarted) {
                await restoreTransport(context.revert.dele);
            } else {
                // Released but never imported: the objects were not deleted, re-importing the copy would overwrite them.
                Logger.log(`Deletion transport ${context.revert.dele.trkorr} was not imported, objects restore skipped`, true);
            }
        } else if (context.revert.updateCleanupTransport
            && await context.revert.updateCleanupTransport.canBeDeleted()) {
            await context.revert.updateCleanupTransport.delete();
        }
    } catch (error) {
        firstError ||= error;
    }
    try {
        if (context.revert.retainedTables) {
            // Old table definitions are imported over the new ones: data is kept.
            await restoreTransport(context.revert.retainedTables);
        } else if (context.revert.updateTablesBackupTransport
            && await context.revert.updateTablesBackupTransport.canBeDeleted()) {
            await context.revert.updateTablesBackupTransport.delete();
        }
    } catch (error) {
        firstError ||= error;
    }
    try {
        await restoreCleanupAssignments(context, false);
    } catch (error) {
        firstError ||= error;
    }
    if (firstError) {
        throw firstError;
    }
}
