import { Inquirer, Logger } from "trm-commons";
import { SystemConnector } from "../../../systemConnector";
import { Transport } from "../../../transport";
import { TransportBinary, TrmPackage } from "../../../trmPackage";
import { AbstractRegistry, RegistryDeletionTransportUnauthorizedError } from "../../../registry";
import { packageDataFromTdevc, getPackageNamespace } from "../../../commons";
import { DEVCLASS, E071, TADIR, TDEVC } from "../../../client";
import { randomBytes } from "crypto";
import type { InstallPackageReplacements } from "../../install";
import { releaseDeletionTransport } from "./releaseDeletionTransport";
import { restoreTransport } from "./restoreTransport";
import { withScopedPrefix } from "./withScopedPrefix";
import { ActionLockScope, objectLockResource } from "./actionLocks";

type CleanupObject = Pick<E071, 'pgmid' | 'object' | 'objName'>;

/** Rollback state written while removing the objects of an installed release. */
export interface PackageCleanupRevert {
    /** SAP packages generated by the action; the cleanup adds its staging package here. */
    sapPackages: DEVCLASS[],
    dele?: TransportBinary,
    cleanupOriginalTadir?: TADIR[],
    cleanupTemporaryPackages?: TDEVC[],
    updateCleanupTransport?: Transport,
    updateTablesBackupTransport?: Transport,
    retainedTables?: TransportBinary,
    /** Set before forwarding the deletion transport, as the TMS queue may change even when the call fails. */
    deleInTargetTms?: boolean
}

/** Minimum workflow context needed to remove an installed release from the target system. */
export interface PackageCleanupContext {
    lockScope?: ActionLockScope,
    rawInput: {
        packageData: {
            name: string,
            registry: AbstractRegistry
        },
        contextData?: {
            noInquirer?: boolean
        }
    },
    runtime?: {
        /** Installed release whose objects are removed. */
        update: TrmPackage,
        /** Install package mappings recorded for the installed release. */
        previousInstallPackages: InstallPackageReplacements[],
        dele?: Transport
    },
    revert?: PackageCleanupRevert
}

/** What remains on the system once the cleanup is complete. */
export type PackageCleanupTarget = {
    /** Objects shipped by the incoming release. Empty when uninstalling. */
    incomingObjects: TADIR[],
    /** SAP packages that hold the incoming release. Empty when uninstalling. */
    keptDevclasses: string[],
    /** Logger/Inquirer prefix shown while the cleanup runs. */
    prefix: string,
    /** Action name used in abort messages, e.g. `Update`. */
    actionName: string,
    /**
     * When `true`, an unauthorized deletion transport request is rethrown after restoring
     * object assignments. Otherwise it only logs a manual cleanup warning.
     */
    requireDeletion: boolean
}

function normalize(value: string): string {
    return value.trim().toUpperCase();
}

function objectKey(object: CleanupObject): string {
    return `${normalize(object.pgmid)}\u0000${normalize(object.object)}\u0000${normalize(object.objName)}`;
}

function isDevclass(object: CleanupObject): boolean {
    return normalize(object.pgmid) === 'R3TR' && normalize(object.object) === 'DEVC';
}

/** Deletes every temporary package, reporting the first failure after the cleanup pass. */
export async function deleteTemporaryCleanupPackages(
    temporaryPackages: Array<Pick<E071, 'objName'>>
): Promise<void> {
    let firstError: unknown;
    for (const devclass of temporaryPackages) {
        try {
            await SystemConnector.deleteTemporaryPackage(devclass.objName);
        } catch (error) {
            firstError ||= error;
        }
    }
    if (firstError) {
        throw firstError;
    }
}

async function restoreCleanupPackages(context: PackageCleanupContext): Promise<void> {
    // Snapshots are stored in deletion order: reverse it to recreate parents first.
    let firstError: unknown;
    for (const pkg of [...(context.revert.cleanupTemporaryPackages || [])].reverse()) {
        try {
            if (await SystemConnector.getDevclass(pkg.devclass)) {
                continue;
            }
            await SystemConnector.createPackage({
                ...packageDataFromTdevc(pkg, {
                    devclass: pkg.devclass,
                    ctext: pkg.ctext || '',
                    as4user: pkg.as4user || SystemConnector.getLogonUser(),
                    dlvunit: pkg.dlvunit,
                    pdevclass: pkg.pdevclass || ''
                }),
                parentcl: pkg.parentcl,
                tpclass: pkg.tpclass
            });
        } catch (error) {
            firstError ||= error;
        }
    }
    if (firstError) {
        throw firstError;
    }
}

async function restoreCleanupAssignments(context: PackageCleanupContext, restorePackages: boolean): Promise<void> {
    if (restorePackages) {
        await restoreCleanupPackages(context);
    }
    await restoreTadirAssignments(context.revert.cleanupOriginalTadir || []);
}

async function restoreTadirAssignments(originals: TADIR[]): Promise<void> {
    if (originals.length === 0) {
        return;
    }
    const existing = new Set((await SystemConnector.getExistingObjects(originals)).map(objectKey));
    let firstError: unknown;
    for (const object of originals) {
        if (existing.has(objectKey(object))) {
            try {
                await SystemConnector.tadirInterface(object);
            } catch (error) {
                firstError ||= error;
            }
        }
    }
    if (firstError) {
        throw firstError;
    }
}

/**
 * Releases a transport of copies with the previous definition of the retained tables,
 * so a rollback can restore them without dropping their data.
 */
async function backupRetainedTables(
    context: PackageCleanupContext,
    retainedTables: CleanupObject[]
): Promise<void> {
    Logger.loading(`Backing up ${retainedTables.length} retained tables...`, true);
    const backup = await Transport.createToc({
        text: `@X1@TRM (BKP) ${context.rawInput.packageData.name} ${context.runtime.update.manifest.get().version}`,
        target: SystemConnector.getDest()
    });
    context.revert.updateTablesBackupTransport = backup;
    await backup.addObjects(retainedTables.map(object => ({
        pgmid: object.pgmid,
        object: object.object,
        objName: object.objName
    })), false);
    await backup.release(false, true);
    context.revert.retainedTables = {
        trkorr: backup.trkorr,
        entries: undefined,
        binaries: (await backup.download()).binaries
    };
}

/**
 * Removes the objects of the installed release (`context.runtime.update`) that are not part
 * of `target`, through a deletion transport generated by the registry.
 *
 * Shared by upgrades, where the target is the incoming release, and by uninstalls, where the
 * target is empty. It also removes SAP packages left empty, locally added objects (after
 * confirmation), and the package namespace when no other package uses it. Tables shipped
 * again by the target are kept and backed up so a rollback preserves their data.
 */
export async function cleanupInstalledPackage(context: PackageCleanupContext, target: PackageCleanupTarget): Promise<void> {
    await withScopedPrefix(target.prefix, async () => {
        const installed = context.runtime.update;
        //1- generate dummy transport
        Logger.loading(`Generating transport...`);
        const dummy = await Transport.createToc({
            text: `@X1@TRM (DELE) ${context.rawInput.packageData.name} ${installed.manifest.get().version}`,
            target: SystemConnector.getDest()
        });
        context.revert.updateCleanupTransport = dummy;
        const previousTransportObjects = installed.getTransport()
            ? await installed.getTransport().getE071()
            : [];
        const incomingObjects = target.incomingObjects;
        // Tables shipped again by the new release are adjusted by its import instead of
        // being dropped and re-created, which would lose their data.
        const incomingKeys = new Set(incomingObjects.map(objectKey));
        const retainedTables = previousTransportObjects.filter(object =>
            normalize(object.pgmid) === 'R3TR' && normalize(object.object) === 'TABL'
            && incomingKeys.has(objectKey(object)));
        const retainedKeys = new Set(retainedTables.map(objectKey));
        retainedTables.forEach(object => Logger.log(`Keeping table ${object.objName} (present in new release)`, true));
        const currentDevclasses = new Set(target.keptDevclasses.map(normalize));
        const previousDevclasses = new Map<string, string>();
        context.runtime.previousInstallPackages.forEach(replacement => {
            previousDevclasses.set(normalize(replacement.installDevclass), replacement.installDevclass);
        });
        // Older installations that kept the publisher package names have no replacement rows.
        if (previousDevclasses.size === 0 && installed.getDevclass()) {
            const previousRoot = installed.getDevclass();
            previousDevclasses.set(normalize(previousRoot), previousRoot);
        }
        previousTransportObjects.forEach(object => {
            if (isDevclass(object)) {
                previousDevclasses.set(normalize(object.objName), object.objName);
            }
        });
        const installedDevclasses = new Set(previousDevclasses.keys());
        const generatedDevclasses = new Set(context.revert.sapPackages.map(normalize));

        // Installation mappings do not include subpackages created locally afterwards.
        // Inspect the live hierarchy even when the installation keeps its root package.
        const packageParents = new Map<string, string>();
        for (const devclass of Array.from(previousDevclasses.values())) {
            for (const subpackage of await SystemConnector.getSubpackages(devclass)) {
                const key = normalize(subpackage.devclass);
                previousDevclasses.set(key, subpackage.devclass);
                if (subpackage.parentcl) {
                    packageParents.set(key, normalize(subpackage.parentcl));
                }
            }
        }

        // Local additions remain cleanup candidates even when reused as incoming targets.
        // The first local package owns the decision for its locally added descendants.
        const cleanupGroups = new Map<string, Set<string>>();
        for (const normalizedDevclass of previousDevclasses.keys()) {
            const locallyAdded = !installedDevclasses.has(normalizedDevclass);
            if (generatedDevclasses.has(normalizedDevclass) || (!locallyAdded && currentDevclasses.has(normalizedDevclass))) {
                continue;
            }
            let root = normalizedDevclass;
            const visited = new Set([root]);
            let parent = packageParents.get(root);
            while (parent && previousDevclasses.has(parent) && !generatedDevclasses.has(parent)
                && (!installedDevclasses.has(parent) === locallyAdded)
                && (locallyAdded || !currentDevclasses.has(parent)) && !visited.has(parent)) {
                root = parent;
                visited.add(root);
                parent = packageParents.get(root);
            }
            if (!cleanupGroups.has(root)) {
                cleanupGroups.set(root, new Set());
            }
            cleanupGroups.get(root).add(normalizedDevclass);
        }

        const changedDevclassesToDelete: string[] = [];
        const extraObjectsToDelete = new Map<string, CleanupObject>();
        for (const [root, group] of cleanupGroups) {
            const devclass = previousDevclasses.get(root);

            // Only objects outside both releases need an extra cleanup decision.
            const objectsAfterImport = new Map<string, TADIR>();
            for (const member of group) {
                for (const object of await SystemConnector.getDevclassObjects(previousDevclasses.get(member), false)) {
                    // Package definitions follow the decision for the whole subtree.
                    if (!isDevclass(object)) {
                        objectsAfterImport.set(objectKey(object), object);
                    }
                }
            }
            previousTransportObjects.forEach(object => objectsAfterImport.delete(objectKey(object)));
            incomingObjects.forEach(object => {
                objectsAfterImport.delete(objectKey(object));
            });

            // Every locally added package definition is an extra object, including
            // the root of this cleanup group, regardless of whether it has contents.
            const packagesToRemove = Array.from(group).filter(member => !currentDevclasses.has(member));
            const extraObjectCount = objectsAfterImport.size + packagesToRemove.filter(member => !installedDevclasses.has(member)).length;
            if (extraObjectCount > 0) {
                const { deleteExtraObjects } = context.rawInput.contextData.noInquirer
                    ? { deleteExtraObjects: true }
                    : await Inquirer.prompt({
                        name: 'deleteExtraObjects',
                        type: 'confirm',
                        message: `Cleanup of SAP package ${devclass}${group.size > 1 ? ' and its subpackages' : ''} will delete ${extraObjectCount} extra objects outside this installation. Continue?`,
                        default: true
                    });
                if (!deleteExtraObjects) {
                    continue;
                }
                objectsAfterImport.forEach((object, key) => extraObjectsToDelete.set(key, {
                    pgmid: object.pgmid,
                    object: object.object,
                    objName: object.objName
                }));
            }
            changedDevclassesToDelete.push(...packagesToRemove.map(member => previousDevclasses.get(member)));
        }

        // A retained child still needs its ancestors, including when cleanup was declined.
        const deletableDevclasses = new Set(changedDevclassesToDelete.map(normalize));
        for (const devclass of previousDevclasses.keys()) {
            if (deletableDevclasses.has(devclass)) {
                continue;
            }
            const visited = new Set<string>();
            let parent = packageParents.get(devclass);
            while (parent && !visited.has(parent)) {
                visited.add(parent);
                deletableDevclasses.delete(parent);
                parent = packageParents.get(parent);
            }
        }
        const packagesToDelete = changedDevclassesToDelete.filter(devclass => deletableDevclasses.has(normalize(devclass)));

        // The namespace itself can only be cleaned up alongside its last remaining package.
        let namespaceToDelete: string;
        if (packagesToDelete.length > 0 && installed.getDevclass()) {
            try {
                const namespace = getPackageNamespace(installed.getDevclass());
                if (namespace.startsWith('/')) {
                    const namespaceExists = await SystemConnector.getNamespace(namespace);
                    if (namespaceExists) {
                        const namespacePackages = await SystemConnector.getNamespacePackages(namespace);
                        const deletingDevclasses = new Set(packagesToDelete.map(normalize));
                        const remainingPackages = namespacePackages.filter(pkg => !deletingDevclasses.has(normalize(pkg.devclass)));
                        if (remainingPackages.length === 0) {
                            namespaceToDelete = namespace;
                        }
                    }
                }
            } catch (e) {
                // devclass doesn't use a custom namespace, nothing to clean up
            }
        }

        // Installed objects moved to a package outside this installation (another TRM package,
        // customer development) are kept unless confirmed.
        const movedObjects = (await SystemConnector.getExistingObjects(previousTransportObjects
            .filter(object => normalize(object.pgmid) === 'R3TR' && !isDevclass(object) && !retainedKeys.has(objectKey(object)))
            .map(object => ({ pgmid: object.pgmid, object: object.object, objName: object.objName, devclass: '' }))))
            .filter(object => object.devclass && !previousDevclasses.has(normalize(object.devclass)));
        const movedKeys = new Set<string>();
        if (movedObjects.length > 0) {
            movedObjects.forEach(object => Logger.warning(`${object.pgmid} ${object.object} ${object.objName} was moved to SAP package ${object.devclass}, outside this installation`));
            const { deleteMovedObjects } = context.rawInput.contextData.noInquirer
                ? { deleteMovedObjects: false }
                : await Inquirer.prompt({
                    name: 'deleteMovedObjects',
                    type: 'confirm',
                    message: `Delete ${movedObjects.length} installed objects moved outside this installation too?`,
                    default: false
                });
            if (!deleteMovedObjects) {
                movedObjects.forEach(object => movedKeys.add(objectKey(object)));
                Logger.warning(`Keeping ${movedObjects.length} objects moved outside this installation.`);
            }
        }

        const additionalObjects = [...extraObjectsToDelete.values(), ...packagesToDelete.map(devclass => ({
            pgmid: 'R3TR',
            object: 'DEVC',
            objName: devclass
        })), ...(namespaceToDelete ? [{
            pgmid: 'R3TR',
            object: 'NSPC',
            objName: namespaceToDelete
        }] : [])];
        // Validate the complete deletion selection before adding anything to the transport.
        const deletionObjects = new Map([...previousTransportObjects, ...additionalObjects]
            .filter(object => !retainedKeys.has(objectKey(object)) && !movedKeys.has(objectKey(object)))
            .map(object => [objectKey(object), object]));
        // TRM comment rows of the installed transport are not objects to delete.
        const hasObjectsToDelete = Array.from(deletionObjects.values()).some(object => normalize(object.pgmid) !== '*');
        if (!hasObjectsToDelete && retainedTables.length === 0) {
            Logger.warning(`Nothing to delete for package ${context.rawInput.packageData.name}: deletion transport was not generated. Manual cleanup of previous release install might be necessary.`);
            try {
                if (await dummy.canBeDeleted()) {
                    await dummy.delete();
                    context.revert.updateCleanupTransport = undefined;
                }
            } catch (e) {
                Logger.warning(`Could not delete transport ${dummy.trkorr}: ${String(e)}`);
            }
            return;
        }
        await context.lockScope.acquire([
            ...Array.from(deletionObjects.values(), objectLockResource),
            ...Array.from(deletionObjects.values())
                .filter(isDevclass)
                .map(object => ({ type: "DEVCLASS" as const, name: object.objName }))
        ]);
        if (deletionObjects.size > 0) {
            Logger.loading(`Checking cleanup objects locks...`, true);
            const locks = await SystemConnector.getObjectsLocks(Array.from(deletionObjects.values(), object => ({
                PGMID: object.pgmid,
                OBJECT: object.object,
                OBJ_NAME: object.objName
            })));
            if (locks.length > 0) {
                locks.forEach(lock => Logger.error(`${lock.pgmid} ${lock.object} ${lock.objName} is currently locked in transport ${lock.trkorr}`));
                throw new Error(`${target.actionName} aborted. To continue, all cleanup objects and SAP packages must be released`);
            }
        }
        const temporaryPackages = Array.from(deletionObjects.values()).filter(object =>
            isDevclass(object) && normalize(object.objName).startsWith('$'));
        const objectsToTransport = Array.from(deletionObjects.values()).filter(object =>
            !temporaryPackages.includes(object));
        // Cleanup exports the previous installation's objects, regardless of the new namespace.
        const needsStaging = normalize(installed.getDevclass() || '').startsWith('$');
        let stagingDevclass: string;
        let retainedOriginalTadir: TADIR[] = [];
        if (needsStaging && (objectsToTransport.length > 0 || retainedTables.length > 0)) {
            // A short-lived, transportable package lets CTS export local objects.
            do {
                stagingDevclass = `ZTRM_DELE_${randomBytes(8).toString('hex').toUpperCase()}`; // 25 characters; DEVCLASS allows 30.
            } while (await SystemConnector.getDevclass(stagingDevclass));
            Logger.loading(`Creating package ${stagingDevclass}...`, true);
            // Track before the mutating await because SAP may commit the package
            // even when the connector response fails.
            context.revert.sapPackages.push(stagingDevclass);
            await SystemConnector.createPackage({
                devclass: stagingDevclass,
                ctext: 'TRM upgrade cleanup',
                as4user: SystemConnector.getLogonUser(),
                dlvunit: 'HOME',
                pdevclass: await SystemConnector.getDefaultTransportLayer()
            });
            await SystemConnector.tadirInterface({
                pgmid: 'R3TR', object: 'DEVC', objName: stagingDevclass,
                devclass: stagingDevclass, srcsystem: 'TRM'
            });
            const existingObjects = await SystemConnector.getExistingObjects(
                [...objectsToTransport, ...retainedTables].map(object => ({
                    pgmid: object.pgmid, object: object.object, objName: object.objName, devclass: ''
                }))
            );
            context.revert.cleanupOriginalTadir = [];
            for (const object of existingObjects) {
                context.revert.cleanupOriginalTadir.push({ ...object });
                if (retainedKeys.has(objectKey(object))) {
                    retainedOriginalTadir.push({ ...object });
                }
                await SystemConnector.tadirInterface({ ...object, devclass: stagingDevclass, srcsystem: 'TRM' });
            }
        }
        if (retainedTables.length > 0) {
            await backupRetainedTables(context, retainedTables);
            // Retained tables stay installed: move them out of the staging package before it is deleted.
            await restoreTadirAssignments(retainedOriginalTadir);
        }
        if (objectsToTransport.length > 0) {
            await dummy.addObjects(objectsToTransport, false);
        }
        if (stagingDevclass) {
            await dummy.addObjects([
                { pgmid: 'R3TR', object: 'DEVC', objName: stagingDevclass }
            ], false);
        }
        const packageDepth = (devclass: string): number => {
            const visited = new Set<string>();
            let parent = packageParents.get(normalize(devclass));
            while (parent && !visited.has(parent)) {
                visited.add(parent);
                parent = packageParents.get(parent);
            }
            return visited.size;
        };
        // Delete descendants before their parents, regardless of transport entry order.
        temporaryPackages.sort((a, b) => packageDepth(b.objName) - packageDepth(a.objName));
        context.revert.cleanupTemporaryPackages = [];
        // Snapshot every definition before deleting any package, including for partial failures.
        for (const devclass of temporaryPackages) {
            const pkg = await SystemConnector.getDevclass(devclass.objName);
            if (!pkg) {
                throw new Error(`Cannot back up temporary SAP package ${devclass.objName}`);
            }
            context.revert.cleanupTemporaryPackages.push({ ...pkg });
        }
        await deleteTemporaryCleanupPackages(temporaryPackages);

        //guard: clean and rebuild comments
        await dummy.removeComments();
        await dummy.addComment(`name=${installed.manifest.get().name}`);
        await dummy.addComment(`version=${installed.manifest.get().version}`);

        try {
            await releaseDeletionTransport(dummy, context.rawInput.packageData.registry, context);
        } catch (e) {
            if (!(e instanceof RegistryDeletionTransportUnauthorizedError)) {
                throw e;
            }
            //at this point the dummy is already released, transport cannot be deleted but it's a harmless release of a transport of copies.
            await restoreCleanupAssignments(context, true);
            if (target.requireDeletion) {
                Logger.error(`User is not authorized to generate deletion transports.`);
                throw e;
            }
            Logger.warning(`User is not authorized to generate cleanup transports. Manual cleanup of previous release install might be necessary.`);
        }
    });
}

/**
 * Whether the deletion transport generated by {@link cleanupInstalledPackage} must be carried
 * through the landscape. Objects of a temporary (`$`) installation only exist on this system.
 */
export function isDeletionForwardable(context: PackageCleanupContext): boolean {
    return !!context.revert.dele && !normalize(context.runtime.update?.getDevclass() || '').startsWith('$');
}

/**
 * Adds the deletion transport to the import queue of the landscape target system, so the
 * removed objects are also deleted there.
 * For a clean landscape, it has to be imported before any transport of a later release.
 */
export async function forwardDeletionTransport(context: PackageCleanupContext, targetSystem: string): Promise<void> {
    // The queue may be changed even when the connector response fails.
    context.revert.deleInTargetTms = true;
    await SystemConnector.forwardTransport(context.revert.dele.trkorr, targetSystem, SystemConnector.getDest(), true);
}

/** Removes the deletion transport from the target system import queue, when it was forwarded. */
export async function revertForwardedDeletionTransport(context: PackageCleanupContext, targetSystem: string): Promise<void> {
    if (context.revert.deleInTargetTms) {
        await SystemConnector.deleteTmsTransport(context.revert.dele.trkorr, targetSystem);
    }
}

/**
 * Rolls back {@link cleanupInstalledPackage}: recreates deleted temporary packages, deletes or
 * re-imports the deletion transport, restores retained tables, and restores object assignments.
 * Every independent operation is attempted; the first failure is thrown afterwards.
 */
export async function revertInstalledPackageCleanup(context: PackageCleanupContext): Promise<void> {
    let firstError: unknown;
    try {
        await restoreCleanupPackages(context);
    } catch (error) {
        firstError = error;
    }
    try {
        if (context.revert.dele) {
            //check if it can be deleted -> the exception might have been raised before the transport release, we can still cleanup nicely
            const transport = new Transport(context.revert.dele.trkorr);
            if (await (transport.canBeDeleted())) {
                await transport.delete();
            } else {
                await restoreTransport(context.revert.dele);
            }
        } else if (context.revert.updateCleanupTransport
            && await context.revert.updateCleanupTransport.canBeDeleted()) {
            await context.revert.updateCleanupTransport.delete();
        }
    } catch (error) {
        firstError ||= error;
    }
    try {
        if (context.revert.retainedTables) {
            // Old table definitions are imported over the new ones: data is kept.
            await restoreTransport(context.revert.retainedTables);
        } else if (context.revert.updateTablesBackupTransport
            && await context.revert.updateTablesBackupTransport.canBeDeleted()) {
            await context.revert.updateTablesBackupTransport.delete();
        }
    } catch (error) {
        firstError ||= error;
    }
    try {
        await restoreCleanupAssignments(context, false);
    } catch (error) {
        firstError ||= error;
    }
    if (firstError) {
        throw firstError;
    }
}
